### ISSUE TITLE
Run render tests OpenGL backend on Linux CI

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-gl-native#1002]

**Comment by mwilsnd** [comment]
There is currently 1 failing test on linux using linux-gcc8-release-style:
```
* errored render-tests/icon-rotate/with-offset
* error: Failed to find gfx probe: probeGFX - default1 - end
```

I think default1 is a typo, @alanchenboy was last to touch that one. Clang metrics work fine so we're OK there.

**Comment by alanchenboy** [comment]
This must be a false update, let me rollback /metrics/linux-gcc8-release/render-tests/icon-rotate/with-offset/metrics.json
