### ISSUE TITLE
Android CamerUpdateFacotry#zoomOut regression

### ISSUE THREAD

**Issue by boldtrn** [maplibre/maplibre-gl-native#1017]
**Describe the bug**
Zoom out leads to zooming to z0.

I think this should be max not min: https://github.com/maplibre/maplibre-gl-native/blob/4828cc7a8be58579b4a2beed8033fefc2fda5170/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraUpdateFactory.kt#L451

Quickfix for users would be: `CameraUpdateFactory.zoomBy(-1.0)`

**Comment by artakka** [comment]
Good catch

**Comment by ovivoda** [comment]
@boldtrn feel free to create a PR for this!

**Comment by boldtrn** [comment]
I created a PR for this: https://github.com/maplibre/maplibre-gl-native/pull/1035
