### ISSUE TITLE
Mapbox GL Native file not found

### ISSUE THREAD

**Issue by karthickkck315** [maplibre/maplibre-gl-native#104]
Hi Team, 
Mapbox GL Navite.xcodeproj file missing. Please find the screenshot. Xcode Version : 12.5. Please suggest me. How can I fix this issue.
<img width="1440" alt="Screenshot 2021-07-05 at 10 19 51 PM" src="https://user-images.githubusercontent.com/4092436/124501415-200b7780-dddf-11eb-8445-77172298ab60.png">

**Comment by petr-pokorny-1** [comment]
MapLibre is using CMake to generate project files, try `make iproj` in `platform/ios` directory or refer to [readme](https://github.com/maplibre/maplibre-gl-native/blob/master/README.md)

**Comment by louwers** [comment]
Please open a thread on [Github Discussions](https://github.com/maplibre/maplibre-gl-native/discussions) if you are still having problems.
