### ISSUE TITLE
iOS MGLMapView missing most commits since Sept 4, 2020

### ISSUE THREAD

**Issue by nnhubbard** [maplibre/maplibre-gl-native#105]
For whatever reason, it seems that `mapLibre` was started using an older version of `mapbox-gl-native-ios`. I have compared the source and it seems that none of the commits since Sept. 4, 2020 have been added in `mapLibre`. See: 

https://github.com/mapbox/mapbox-gl-native-ios/commits/main/platform/ios/src/MGLMapView.mm

Some of these are very important such as https://github.com/mapbox/mapbox-gl-native-ios/commit/86891739543d6cc3049924e68bbc70ec2c1c5870#diff-2b12ba2cacef0e8c6a943690a80480a938985ff758d0b69cae5913c8d3cf9273 which clearly is still buggy in `mapLibre` because the fix has not been merged. 

Are there plans to merge all of the fixes to `MGLMapView` that are in the `mapbox-gl-native-ios` project?

**Comment by petr-pokorny-1** [comment]
The mapbox-gl-native was forked from [d60fd30 - mgbl 1.6.0](https://github.com/mapbox/mapbox-gl-native/tree/d60fd302b1f6563e7d16952f8855122fdcc85f73), mapbox-gl-native-ios from [a139216](https://github.com/mapbox/mapbox-gl-native-ios/commit/a139216) and mapbox-gl-native-android from [4c12fb2](https://github.com/mapbox/mapbox-gl-native-android/commit/4c12fb2c)

mapbox-gl-native-ios and mapbox-gl-native-android depends on the core library (mapbox-gl-native) which was moved behind curtains by MapBox after May 7 2020 and code changes are no longer available for open-source community. So we took ios/android at the most recent version which is compatible (meaning it compiles and links) with the core library. Many commits in mapbox-gl-native-ios and mapbox-gl-native-android after this date have dependency on the core library and it is not possible simply cherry-pick them. From those with no dependency, we have cherry-picked some of them (please see the PR history) but some still remains to be cherry-picked.

Here is a list of changes which could be potentially cherry-picked.
We would welcome any help to break down these into tickets in this repo and cherry-pick them. The work is to inspect original changes, see if they were already done in MapLibre, check if the have any dependency on changes in the core library and create PR with cherry-picked changes.

Platform | Title | Link
-- | -- | --
iOS | Explore: Expose styling for default user location view | https://github.com/mapbox/mapbox-gl-native-ios/pull/403
iOS | Ask accuracy authorization when tracking mode is different from none | https://github.com/mapbox/mapbox-gl-native-ios/pull/406
iOS | Switch background snapshot to periodic. | https://github.com/mapbox/mapbox-gl-native-ios/pull/412
iOS | Add a flag to enforce using cached tiles | https://github.com/mapbox/mapbox-gl-native-ios/pull/416
iOS | Fix content insets when automaticallyAdjustsScrollViewInsets is set to NO | https://github.com/mapbox/mapbox-gl-native-ios/pull/420
iOS | Address crash when localFontFamilyName is nil | https://github.com/mapbox/mapbox-gl-native-ios/pull/467
iOS | Location manager crash fix when a selector is not implemented | https://github.com/mapbox/mapbox-gl-native-ios/pull/474
iOS | Add compass image as a sublayer | https://github.com/mapbox/mapbox-gl-native-ios/pull/501
iOS | Fix scalebar ornament triggers unnecessary layoutSubviews | https://github.com/mapbox/mapbox-gl-native-ios/pull/507
iOS | Fix issue: approximate Location indicator disappears at high zoom | https://github.com/mapbox/mapbox-gl-native-ios/pull/531
iOS | Fix an issue where updating .followWithHeading prevents annotation's location updates | https://github.com/mapbox/mapbox-gl-native-ios/pull/580
Android | Use weak references for Layer and Source API | https://github.com/mapbox/mapbox-gl-native-android/pull/432https://github.com/mapbox/mapbox-gl-native-android/pull/516
Android | Update http cancel log. | https://github.com/mapbox/mapbox-gl-native-android/pull/433
Android | Smooth puck animation after changing style. | https://github.com/mapbox/mapbox-gl-native-android/pull/437
Android | Add background image for GPS mode in IndicatorLocationLayerRender. | https://github.com/mapbox/mapbox-gl-native-android/pull/439
Android | Set gps bearing immediately while changing to gps mode. #470 | https://github.com/mapbox/mapbox-gl-native-android/pull/470
Android | Add http hook | https://github.com/mapbox/mapbox-gl-native-android/pull/472
Android | Expose animation handling | https://github.com/mapbox/mapbox-gl-native-android/pull/491
Android | [offline] remove world bounds validation when creating an offline region | https://github.com/mapbox/mapbox-gl-native-android/pull/495
Android | Implement method to set padding when camera is tracking. | https://github.com/mapbox/mapbox-gl-native-android/pull/496
Android | call setUserAnimationInProgress in LocationCameraController | https://github.com/mapbox/mapbox-gl-native-android/pull/501
Android | Check isLocationTracking in the right place | https://github.com/mapbox/mapbox-gl-native-android/pull/504
Android | Expose indicator position change listener | https://github.com/mapbox/mapbox-gl-native-android/pull/515
Android | [testapp] fixup onSaveInstanceState usage | https://github.com/mapbox/mapbox-gl-native-android/pull/539
Android | [style] add image array support | https://github.com/mapbox/mapbox-gl-native-android/pull/544
Android | Crash when converting screencoordinate as part of moveBy | https://github.com/mapbox/mapbox-gl-native-android/pull/555
Android | Fix Style not ready exception in locationcomponent | https://github.com/mapbox/mapbox-gl-native-android/pull/563https://github.com/mapbox/mapbox-gl-native-android/pull/620
Android | Fix pulse circle opacity calculate error | https://github.com/mapbox/mapbox-gl-native-android/pull/625

**Comment by nnhubbard** [comment]
I created a PR for https://github.com/mapbox/mapbox-gl-native-ios/pull/406:

https://github.com/maplibre/maplibre-gl-native/pull/108

**Comment by nnhubbard** [comment]
https://github.com/mapbox/mapbox-gl-native-ios/pull/412 is already in `mapLibre`.
