### ISSUE TITLE
Can't build 5.12 or 5.11?

### ISSUE THREAD

**Issue by nvanfleet** [maplibre/maplibre-gl-native#110]
I checked out the repo and tried to build 5.12 but I get an error. I haven't modified anything and had checked out the tag for 5.12 and even tried 5.11

```
nathanvanfleet@nvanfleet-MBP114:~/src/maplibre-gl-native/platform/ios$ make iproj
mkdir -p build/ios
(cd build/ios && cmake -G Xcode ../../../../ \
		-DCMAKE_SYSTEM_NAME=iOS )
-- Configuring GL-Native with OpenGL renderer backend
CMake Error at vendor/mapbox-base.cmake:4 (add_subdirectory):
  The source directory

    /Users/nathanvanfleet/src/maplibre-gl-native/vendor/mapbox-base

  does not contain a CMakeLists.txt file.
```

**Comment by roblabs** [comment]
I don't think these are the root problem, but you can verify:

1. As of this writing, we only support up to Xcode `12.4`
2. Do you have all the Git Submodules:  e.g., `git clone --recurse-submodules`
3. Please verify that you have the dependencies listed here.  These are what the Continuous Integration scripts rely on:

https://github.com/maplibre/maplibre-gl-native/blob/master/.github/workflows/ios-ci.yml#L42-L45

**Comment by nnhubbard** [comment]
Also make sure to install all of the requirements: https://github.com/maplibre/maplibre-gl-native/blob/master/platform/ios/platform/ios/INSTALL.md

**Comment by nvanfleet** [comment]
Okay that seems to be it. I can see there is no recurse submodules command here though btw https://github.com/maplibre/maplibre-gl-native/blob/master/platform/ios/platform/ios/INSTALL.md#building-the-sdk

**Comment by nnhubbard** [comment]
@nvanfleet Most of the stuff on that INSTALL document is from the old mapbox install. Just the first requirements section is relevant.

**Comment by nvanfleet** [comment]
@nnhubbard  does something like `make iframework FORMAT=static BUILDTYPE=Release` still work? I am trying to get it to work but am not sure if it's still functional

**Comment by xurenzhong** [comment]
mkdir -p build/ios
(cd build/ios && cmake -G Xcode ../../../../ \
                -DCMAKE_SYSTEM_NAME=iOS )
-- Configuring GL-Native with OpenGL renderer backend
CMake Error at scripts/license.cmake:24 (message):
  License not found for target: Mapbox::Base::shelf-pack-cpp
Call Stack (most recent call first):
  scripts/license.cmake:40 (mbgl_generate_license)
  CMakeLists.txt:1038 (include)


-- Configuring incomplete, errors occurred!

happened to me in m1x mac, how to fix it?
