### ISSUE TITLE
Provide a way to compile iOS into a static framework

### ISSUE THREAD

**Issue by nvanfleet** [maplibre/maplibre-gl-native#111]
Currently the scripts for building are only capable of producing a dynamic build of the SDK. We use static builds for our dependencies and so having the ability to build one using the build scripts would be ideal.

**Comment by wipfli** [comment]
Is this still an open issue, @nvanfleet?

**Comment by nvanfleet** [comment]
@wipfli I suppose it is. The static build was broken. I was looking into fixing it but it ultimately wasn't possible at the time. Though I ended up writing a bagel build file to accomplish it. But I think it's still "open" in the sense that static building is broken on maplibre master.

**Comment by wipfli** [comment]
Aha good to know, thanks, @nvanfleet

**Comment by birkskyum** [comment]
@nvanfleet , This is working with bazel now right?

**Comment by nvanfleet** [comment]
@birkskyum oh yes it absolutely is. I think this can definitely be closed now
