### ISSUE TITLE
WatchOS Support?

### ISSUE THREAD

**Issue by emanuelelaface** [maplibre/maplibre-gl-native#12]
Hi, have you considered to add the support for WatchOS? I think it would open a gigantic market of outdoors the possibility to use vector maps on the Watch.

**Comment by petr-pokorny-1** [comment]
The original Mapbox SDK from which MapLibre SDK si forked did not have support for WatchOS. We will not implement it now.

**Comment by louwers** [comment]
@robertgreso MapLibre Native focusses on real-time rendering of vector based maps. I think the existing apps for the WatchOS use raster maps with some simple Quartz vectors. You could render with MapLibre Native on the phone and stream that to the watch, but it is out of scope for this project.

If Apple were to support Metal on watchOS, that would change things.
