### ISSUE TITLE
Boost MSVC 2019 Compile Issues

### ISSUE THREAD

**Issue by dpaulat** [maplibre/maplibre-gl-native#124]
vendor/boost has compile issues when compiling with MSVC 2019.  See https://github.com/mapbox/mapbox-gl-native-boost/pull/2.  I can think of two potential resolutions:

1. mapbox-gl-native-boost needs forked
2. Use a package manager (e.g., conan)

The latter could also help with other missing dependencies (e.g., zlib), if the project wants to move in this direction.

**Comment by kiibimees** [comment]
Conan might introduce annoying yet-another-tool-dependency. Forking and updating _mapbox-gl-native-boost_ seems to be a clean enough soution, IMHO. Any dependency to Mapbox should be removed in the future anyway, I guess.

**Comment by kiibimees** [comment]
Or why not just copy and commit all boost files directly into this repository? Boost itselt doesn't have a 'release' repo and I don't see any good reason why should we create it and make things more compicated. It's a header-only usage.

**Comment by dpaulat** [comment]
I think your suggestion of forking mapbox-gl-native-boost is the most
straightforward solution.  It's a vendor dependency, following the pattern
of most other dependencies in the vendor directory, would make sense to
have it a submodule.  It makes it easier to interchange dependencies, and
there could be a point in the future where it's more than header-only usage.

**Comment by kiibimees** [comment]
Sure, fine by me. Could somebody with enough ranking do it in the near future? Right now MSVC 2019 build fails because of that.

**Comment by dpaulat** [comment]
If you're looking for a temporary solution while waiting for the fork, I fixed the immediate issue in a fork, without upgrading boost:

https://github.com/dpaulat/mapbox-gl-native-boost

**Comment by kiibimees** [comment]
Well, it would be nice if I could just point QtLocation submodule to a maplibre state where it is fixed. In that case one can compile the plugin more easily. An super-cool would be if somebody could review my [merge request](https://github.com/maplibre/maplibre-gl-native/pull/197). That makes short URL-s and styles also work with the plugin. Then I would be very happy for the start. Later, I would like to handle style types (streets, hybrid, terrain, etc) more correctly but that is not a showstopper anymore.

**Comment by kiibimees** [comment]
It would be nice if somebody with enough ranking, fork the mapbox boost repo and add at least the MSVC fix.

Anybody?

**Comment by kiibimees** [comment]
I would be so much appreciated if somebody could fork the Boost repo and apply necessary fixes. Anubody?
