### ISSUE TITLE
iOS 14.5 / Xcode 12.5 Build Issue:  Semantic Issue (Comparison of distinct pointer types)

### ISSUE THREAD

**Issue by roblabs** [maplibre/maplibre-gl-native#14]
There is a compiler error when building the scheme `dynamic` with Xcode.

Tested against:
* Version 12.5 (12E262) released on Apr 20, 2021
* Version 12.5 beta 3 (12E5244e) released on Mar  2, 2021.
* Version 12.5 beta 2 (12E5234g) released on Feb 16, 2021.
* Version 12.5 Beta (12E5220o) released on Feb 1, 2021.

This same file (`NSExpression+MGLAdditions.mm`) compiles fine with Xcode Version 12.4 (12D4e) & Xcode Version 11.7 (11E801a)

---

Xcode reports *Semantic Issue*

> Comparison of distinct pointer types ('NSString *' and 'Class')

---

https://github.com/maptiler/maplibre-gl-native/blob/72692d6305bb4df1d64dab450e0d49e2c8d5c943/platform/ios/platform/darwin/src/NSExpression%2BMGLAdditions.mm#L1272

---

*Error in Xcode 12.5 Beta* 

![image](https://user-images.githubusercontent.com/118112/106685922-3e462080-657e-11eb-8296-52f3c67f51c6.png)

---

Other parameters of note:

* SDK iOS 14.5 (released as Beta on Feb 1, 2021)

![image](https://user-images.githubusercontent.com/118112/106687422-eceb6080-6580-11eb-8b16-f1d31686f620.png)

**Comment by roblabs** [comment]
New type of error when attempting to build with Version 12.5 beta 3 (12E5244e) when testing with master: dba5d968b21a05d52ad5aa7b261804f032d0736f

> Cast to smaller integer type 'unsigned int' from 'MGLReachability *'

![image](https://user-images.githubusercontent.com/118112/113783080-0d9e7680-96e8-11eb-8613-d64ce20727ea.png)

**Comment by roblabs** [comment]
This issue still exists & is a blocker for anyone intending to upgrade to Xcode 12.5 RC for MapLibre development.  I recommend sticking with Xcode 11.7 or 12.4 to build MapLibre.

**Comment by roblabs** [comment]
If you are keen to upgrade to Xcode 12.5, you can help investigate or make a test case to ensure that the following is the right fix and/or a proper workaround.

```swift
//                           (NSString *) // Fixing the error by casting.  TODO verify it doesn't break something else
            } else if (op == (NSString *) [MGLColor class] && [function isEqualToString:@"colorWithRed:green:blue:alpha:"]) {
```

---
*Diff from within Xcode 12.5*
![image](https://user-images.githubusercontent.com/118112/116341259-6d42eb80-a795-11eb-8773-93fc72d5f0a2.png)

**Comment by glyuck** [comment]
Regarding the error in `MGLReachability.m` and `Cast to smaller integer type 'unsigned int' from 'MGLReachability *'` warning:
I think we should replace
```
    NSString *description = [NSString stringWithFormat:@"<%@: %#x (%@)>",
                             NSStringFromClass([self class]), (unsigned int) self, [self currentReachabilityFlags]];
```
with
```
    NSString *description = [NSString stringWithFormat:@"<%@: %p (%@)>",
                             NSStringFromClass([self class]), (void *) self, [self currentReachabilityFlags]];
```

The first warning `Comparison of distinct pointer types ('NSString *' and 'Class')`:
```
} else if (op == [MGLColor class] && [function isEqualToString:@"colorWithRed:green:blue:alpha:"]) {
```
It looks like a bug in Mapbox source code to me: `op == [MGLColor class]` the left variable is `NSString *` and the right one is `Class`. I can't figure out how it supposed to work.
Probably it should be something like `[op isEqualToString:NSStringFromClass([MGLColor class])]`

**Comment by roblabs** [comment]
@glyuck — thanks for the contribution!  

With this commit we now support Xcode 12.5 & Xcode 13-beta.  And as a bonus MapLibre runs on the simulator on Apple Silicon with the latest Xcode release & beta.

Commit https://github.com/maplibre/maplibre-gl-native/commit/19b86f750dd829a1122a1df928709c70e62cbeeb been has tested on:
* both flavors of Big Sur (Intel & arm)
* a couple of Xcode versions that I had lying around

| **Xcode Version**         | **c++ version**     | **Catalina** | **Big Sur (Intel)** | **Big Sur (arm)**
| :---                  | :--- | :--- | :--- | :--- |
| 12.4 (12D4e)          | 12.0.0.12000032       | ✅<sup>*Xcode 12.4 runs on Catalina & Big Sur*</sup> | ✅ | *Not tested*
| 12.5.1 (12E507)       | 12.0.5.12050022       | ❌<sup>*Xcode 12.5 requires Big Sur*</sup> | ✅ | ✅
| 13.0 (13A5192i)       | 13.0.0.13000025       | ❌<sup>*Xcode 13-beta requires Big Sur*</sup> | ✅ | ✅
