### ISSUE TITLE
Bazel build configuration

### ISSUE THREAD

**Issue by keith** [maplibre/maplibre-gl-native#155]
Hey folks, we currently build our iOS app with [bazel](https://bazel.build/), this provides us a lot of benefits like reproducibility and declarative build configurations. I'm curious if this project would be willing to accept the hand written bazel build configuration we've written for this repo, so it could be used by other folks who are integrating this library, and be tested on CI as build configuration changes over time.

**Comment by roblabs** [comment]
@Keith — Bazel would be welcome.  PRs are welcome and I think placing it _near_ where `.github` workflow would be perfect, e.g. `.bazel`?!?.  I leave it up to you where to place it.  Please add any useful notes to the README.

---

![image](https://user-images.githubusercontent.com/118112/132058268-a87173eb-4ede-42bc-b93d-4d2f4781d31b.png)

**Comment by keith** [comment]
Awesome! I'll try to cleanup what we have internally a bit and submit something for discussion. Unfortunately at least some configuration files have to be in specific places (like the root of the repo) but I will try to keep it to a minimum!

**Comment by birkskyum** [comment]
cllosed by #419
