### ISSUE TITLE
Symbol layer flickering after zooming out

### ISSUE THREAD

**Issue by moodstubos** [maplibre/maplibre-gl-native#16]
Mapbox 6.0 got an update for this (unfortunately after license change):

> 🐞 Bug fixes
> Fixed an issue where symbols flickered when zooming out. (mapbox/mapbox-gl-native#16471, mapbox/mapbox-gl-native-ios/issues/273)

source 1: https://github.com/mapbox/mapbox-gl-native-ios/blob/master/platform/ios/CHANGELOG.md
source 2: https://github.com/mapbox/mapbox-gl-native/issues/16473#issuecomment-661255009

Found this issue in maplibre-gl-native android as well as ios.

Unfortunately I could not find any original commit in mapbox-gl-native repo for the mentioned fixes. I pretty sure its in the closed code therefore.

Perhaps someone has an idea where to begin for fixing this. 
By the way: older versions of mapbox-gl-native-android (e.g. 8.6.7) does not have this issue (not yet tested for older ios versions).

**Comment by ystsoi** [comment]
Hi, I am the reporter of the issue https://github.com/mapbox/mapbox-gl-native/issues/16471. Actually, I have a custom patch for some flickering issues, and I have uploaded it to https://github.com/ystsoi/maplibre-gl-native/commit/52c2ce749dcdf3543ca60b012b6207627851356c. The patch is for Mapbox, and I have not tested it against MapLibre. However, I think that it should work on MapLibre too, please try it.

**Comment by petr-pokorny-1** [comment]
Thanks for help @ystsoi !
I have tested it on Android. [Here is video before fix](https://drive.google.com/file/d/1b4bn4L8iwOTOWDGR3TOgcxHgVxuUQiyV/view?usp=sharing)

And here [after applying the patch](https://drive.google.com/file/d/1Zz1VAT3Gu3-K7qbwzwoKAQg6PiaxAuKd/view?usp=sharing)

**Comment by moodstubos** [comment]
@ystsoi 
thank you so much for sharing your patch!!
I just tried and it completly prevents flickering.

**Comment by gokugen** [comment]
Hi, thank you for the patch! It works pretty well on Android.
However i'm still facing this issue on IOS... Did you find a solution for this ?

**Comment by gokugen** [comment]
Update: After upgrading Mapbox IOS SDK to the last version using [https://github.com/react-native-mapbox-gl/maps/blob/master/ios/install.md#mapbox-maps-sdk](url) the problem disappear!

**Comment by ferdicus** [comment]
@gokugen, the provided link you've posted has nothing to do with MapLibre though - I'm posting this to make you aware of that. 

THIS repo is _MapLibre_, when you follow the steps in (https://github.com/react-native-mapbox-gl/maps/blob/master/ios/install.md#mapbox-maps-sdk ) you will update the SDK version of the _Mapbox_ iOS SDK, not of the MapLibre SDK.
