### ISSUE TITLE
MabLibre marker has not set or get Rotation

### ISSUE THREAD

**Issue by peteresteris** [maplibre/maplibre-gl-native#164]
Hi people
I am newbe with MapLibre. I have worked with Leaflet but has not rotation. I have also worked with openlayers which has rotation but haas not pitching (tilt). I used ol-ext perspective map but is in my opinion an incompleted library cause' has troubles for example centered map, or padding, etc.
Well, I found MapLibre which has a very high performance superior to the other two. 
I am working in Ionic 6.17.0 and I first tried to use directly maplibre-gl library but I had several types troubles, lacks of package like geojson, and many others. Then, I try ngx-maplibre-gl but when I used mgl-map and other components they do nothing on my view.
Finally, I used maplibre-gl installed by ngx-maplibre-gl without using last one and works.
But, I found my first issue when I try to rotate a marker. Curiosly, in the docs marker has rotation, getRotation and setRotation but when I initialized marker has rotation property but has not the others two. However, it has setRotationAlignment. 
IT IS VERY WEIRD

This is my package.json:
{
  "name": "Maplibre",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "~12.1.1",
    "@angular/core": "~12.1.1",
    "@angular/forms": "~12.1.1",
    "@angular/platform-browser": "~12.1.1",
    "@angular/platform-browser-dynamic": "~12.1.1",
    "@angular/router": "~12.1.1",
    "@capacitor/app": "1.0.3",
    "@capacitor/core": "3.2.4",
    "@capacitor/haptics": "1.1.0",
    "@capacitor/keyboard": "1.1.0",
    "@capacitor/status-bar": "1.0.3",
    "@ionic/angular": "^5.5.2",
    "@types/geojson": "^7946.0.8",
    "maplibre-gl": "^1.15.2",
    "ngx-maplibre-gl": "^12.0.0",
    "rxjs": "~6.6.0",
    "tslib": "^2.2.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~12.1.1",
    "@angular-eslint/builder": "~12.0.0",
    "@angular-eslint/eslint-plugin": "~12.0.0",
    "@angular-eslint/eslint-plugin-template": "~12.0.0",
    "@angular-eslint/template-parser": "~12.0.0",
    "@angular/cli": "~12.1.1",
    "@angular/compiler": "~12.1.1",
    "@angular/compiler-cli": "~12.1.1",
    "@angular/language-service": "~12.0.1",
    "@capacitor/cli": "3.2.4",
    "@ionic/angular-toolkit": "^4.0.0",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "@typescript-eslint/eslint-plugin": "4.16.1",
    "@typescript-eslint/parser": "4.16.1",
    "eslint": "^7.6.0",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jsdoc": "30.7.6",
    "eslint-plugin-prefer-arrow": "1.2.2",
    "jasmine-core": "~3.8.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.3.2",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "typescript": "~4.2.4"
  },
  "description": "An Ionic project"
}

![imagen](https://user-images.githubusercontent.com/53539821/136634630-23bba152-7f82-4ff2-acde-1db6e8116eb5.png)

![imagen](https://user-images.githubusercontent.com/53539821/136634873-7631dfec-4e7a-465c-9751-0960fb724b1b.png)

Please, Could anyone help me??

**Comment by peteresteris** [comment]
In the official documentation [](https://maplibre.org/maplibre-gl-js-docs/api/markers/#marker-parameters) library has get and setRotation methods.
I believe that I have a version trouble between official and ngx-maplibre-gl.

**Comment by birkskyum** [comment]
Hi @peteresteris , I believe this issue belongs in this repository

https://github.com/maplibre/maplibre-gl-js
