### ISSUE TITLE
How "Mapbox Maps SDK for macOS" should be named?

### ISSUE THREAD

**Issue by matkoniecz** [maplibre/maplibre-gl-native#170]
It seems to me that it likely should be renamed - see https://github.com/maplibre/maplibre-gl-native/tree/master/platform/ios/platform/macos#mapbox-maps-sdk-for-macos

For reason starting from fact that this project likely should not use Mapbox trademark (both as it is likely legally problematic and because promoting own brand would be useful).

**Comment by wipfli** [comment]
#318

**Comment by louwers** [comment]
We went with MapLibre GL Native for macOS for now.
