### ISSUE TITLE
MGLMapView.centerCoordinate inconsistent padding reset

### ISSUE THREAD

**Issue by nvanfleet** [maplibre/maplibre-gl-native#171]
MGLMapView interface contains a method

```
func setCamera(MGLMapCamera, withDuration: TimeInterval, animationTimingFunction: CAMediaTimingFunction?, edgePadding: UIEdgeInsets, completionHandler: (() -Void)?)
```

that takes edgePadding as an argument and applying it, it adjusts `centerCoordinate` of the map (on the video `centerCoordinate` is marked as green square). But there is inconsistency how user interaction (and programmatic camera updates) resets this adjustment. As you can see on the video pan gesture doesn't reset adjustment but pinch gesture do. Also there is no way to check if current `centerCoordinate` is actually adjusted or not.

<img alt="" width="350" src="https://user-images.githubusercontent.com/1486399/137390356-7c2e09b2-7f49-45af-a3cf-6f331c3cf70d.gif">

### Steps to reproduce
1. Setup camera
2. call (on the video called on "setWithPadding" tap)

```
let edgePadding = UIEdgeInsets(top: 0, left: 0, bottom: 250, right: 0)
mapView.setCamera(newCamera, withDuration: 0.5, animationTimingFunction: nil, edgePadding: edgePadding)
```

 1. observe `mapView.centerCoordinate` (green square on the video, added as MGLPointAnnotation and position is updated in delegate `regionDidChange` method) it's adjusted according to passed `edgePadding` from step 2.
2. move map with pan gesture, observe that `mapView.centerCoordinate` remains adjusted
3. zoom map with pinch gesture, observe that `mapView.centerCoordinate` resets to the map center

### Expected behavior
I'd expect consistent behavior, either reset adjustment after any map interaction or remain of adjustment after any map interaction(but it's not clear how to reset it then)

### Actual behavior
`mapView.centerCoordinate` adjustment is reset by zoom gesture and not reset by pan gesture

### Configuration
**Mapbox SDK versions:** 6.3.0, 5.6.1 **iOS/macOS versions:** 14.4 **Device/simulator models:** simulator iPhone 8 **Xcode version:** 12.4

Copied from: https://github.com/mapbox/mapbox-gl-native-ios/issues/604

**Comment by OlexandrStepanov** [comment]
@nvanfleet , can this issue be closed now with my PR merged to the project?
