### ISSUE TITLE
visibleAnnotations is nil but the annotations are there and visible

### ISSUE THREAD

**Issue by dieterdreist** [maplibre/maplibre-gl-native#176]
In my app, mapView.visibleAnnotations is always nil, although I see the annotations in mapView.annotations, and I see them on the map, and their coords are within the visible MapRect. I am using a custom MGLAnnotation and a custom MGLAnnotationView (both of which have worked together fine in MapKit). Someone else experiencing this problem?
I am adopting the MGLAnnotation protocol (by proving a "coordinate", "title" and "subtitle" in my custom annotation), is there more to do?

**Comment by louwers** [comment]
Closed since this is likely the same issue as #187.

Please re-open (if possible with a reproduction) if this is still an issue.
