### ISSUE TITLE
Offline download crashes

### ISSUE THREAD

**Issue by m0nac0** [maplibre/maplibre-gl-native#177]
In the flutter bindings we are seeing this crash https://github.com/m0nac0/flutter-maplibre-gl/issues/39 when downloading e.g. regions from the source `https://demotiles.maplibre.org/style.json` in our test/example app.

I suspect it has to do something with the new regex validations introduced here https://github.com/maplibre/maplibre-gl-native/blob/master/src/mbgl/util/mapbox.cpp as part of the migration to Maplibre. But I couldn't find any documentation for offline downloads. 

Are there different requirements for source URLs for offline downloads compared to those for regular map displays?

**Comment by JanikoNaber** [comment]
The download function is a important feature for our App. Is there any update on this issue?

**Comment by ntadej** [comment]
A self-contained reproducer would help a lot in fixing this faster. Do you think you could prepare it?

**Comment by JanikoNaber** [comment]
I can only reference to to flutter binding example: https://github.com/m0nac0/flutter-maplibre-gl/tree/main/example 
Downloading a region results in a crash, descripted in https://github.com/m0nac0/flutter-maplibre-gl/issues/39
But therefore you need flutter to be installed. @m0nac0 can you provide a reproducer without flutter?

**Comment by m0nac0** [comment]
> @m0nac0 can you provide a reproducer without flutter?

Sorry, I probably won't have enough time to try to reproduce this without flutter.

**Comment by louwers** [comment]
[DemoTiles](https://github.com/maplibre/demotiles) is hosted on GitHub Pages and does not work with the offline download. Please use another tile server to try out offline support.

**Comment by noorbakerally** [comment]
Any success on this issue, is it because of the DemoTiles?

**Comment by louwers** [comment]
Hello @noorbakerally, I tried out offline support with the demo tiles which failed while a 'normal' tile server worked. If you run into any issues feel free to create an issue!
