### ISSUE TITLE
Qt Location support on Windows with MSVC

### ISSUE THREAD

**Issue by srcejon** [maplibre/maplibre-gl-native#181]
Qt Location 5 on Windows with msvc doesn't support the Mapbox GL plugin (because mapbox-gl-native couldn't be compiled with msvc. However, thanks to @dpaulat maplibre-gl-native can.). So is it possible to use maplibre-gl-native in Qt Location?

The readme in platform/qt says 'This is the foundation for the Mapbox GL plugin' - but it doesn't appear to be the plugin itself. Qt seems to want qtgeoservices_mapboxql.dll, but QMapboxGL.dll is built (which doesn't include qt_plugin_instance so doesn't appear to be a plugin). Any ideas how to proceed?

**Comment by srcejon** [comment]
It seems Qt has a fork of mapbox-gl-native in its [source tree](https://github.com/qt/qtlocation-mapboxgl/tree/d3101bbc22edd41c9036ea487d4a71eabd97823d).

With a few changes, as described [here](https://bugreports.qt.io/browse/QTBUG-74463), it seems it is possible to get Qt Location to build with maplibre-gl-native.

**Comment by kiibimees** [comment]
I recommend to switch to Qt6. There is a patch that builds also on MSVC 2019 in [here](https://codereview.qt-project.org/c/qt/qtlocation/+/382087), with the exception that one Boost library bug has to be applied.

Read more in this discussion: https://github.com/maplibre/maplibre-gl-native/issues/42

**Comment by birkskyum** [comment]
https://github.com/maplibre/maplibre-gl-native/releases/tag/qt-v2.0.0
