### ISSUE TITLE
API to set feature state and promoteId missing

### ISSUE THREAD

**Issue by sujithkris** [maplibre/maplibre-gl-native#185]
**Environment**

- Xcode version: 13.1 (13A1030d)
- iOS version: 15
- Devices affected: All
- maplibre-gl-native 5.9.0

Not finding the js equivalent of `setFeatureState` method for MGLMapView and setter `promoteId` for VectorSource.

**Comment by wipfli** [comment]
Hi @sujithkris. Thanks for reporting. I guess the problem is that feature state is not implemented yet in native, see https://maplibre.org/maplibre-gl-js-docs/style-spec/expressions/#feature-state for the documentation of the supported SDKs.

**Comment by sujithkris** [comment]
@wipfli  : Is there any plan in the roadmap to support feature state in native SDKs?
