### ISSUE TITLE
[qt] mapbox:// URI not supported

### ISSUE THREAD

**Issue by rinigus** [maplibre/maplibre-gl-native#193]
When trying to access mapbox:// styles, turned out that they are not converted to https:// URI when using Qt bindings.  

Doing a quick search, I couldn't figure out what's missing in Qt bindings. Is this a known bug? Any pointers on how to fix it?

**Comment by rinigus** [comment]
Issue seems to be related to the fact that `QMapboxGLSettings::QMapboxGLSettings()` takes `mbgl::TileServerOptions::DefaultConfiguration()` in the constructor. Not sure how to proceed with it further as I don't find a knob allowing flexibility in terms of specifying a style with any of the supported URI schemes.

**Comment by kiibimees** [comment]
I got the same problem and made a [merge request](https://github.com/maplibre/maplibre-gl-native/pull/197) to make it possible to switch between different settings template. Right now it satisfies the use cases where Mapbox or MapTiler services are used. In case somebody wants to set up it's own server, we need expose all `mbgl::TileServerOptions` parameters also in `QMapboxGLSettings`. To be able to fine-tune everything.

**Comment by rinigus** [comment]
@kiibimees: what I cannot figure out with the proposed solution is how to make it simple for user to switch from `mapbox://` to `maptiler://` on QML level. It seems that we will have to start parsing style URL at QML plugin level and then start switching the backends. Which seems to cause having all mappings defined in QML plugin and QMapboxGL - something we will have to keep in sync in different codebases.

**Comment by rinigus** [comment]
Resolved with #197 

Closing here. There is a more general issue with the support for different URI schemes, but that is probably better to file separately.
