### ISSUE TITLE
[iOS] make iframework BUILDTYPE=Release : CMake Error at scripts/license.cmake

### ISSUE THREAD

**Issue by xurenzhong** [maplibre/maplibre-gl-native#194]
I created custom framework, and error happened:

mkdir -p build/ios
(cd build/ios && cmake -G Xcode ../../../../ \
                -DCMAKE_SYSTEM_NAME=iOS )
-- Configuring GL-Native with OpenGL renderer backend
CMake Error at scripts/license.cmake:24 (message):
  License not found for target: Mapbox::Base::shelf-pack-cpp
Call Stack (most recent call first):
  scripts/license.cmake:40 (mbgl_generate_license)
  CMakeLists.txt:1038 (include)

-- Configuring incomplete, errors occurred!
See also "/Users/renzhongxu/maplibre-gl-native/platform/ios/build/ios/CMakeFiles/CMakeOutput.log".
make: *** [build/ios/Mapbox GL Native.xcodeproj] Error 1

Device: m1 mac
xcode: 13

**Comment by xurenzhong** [comment]
A mistake from my own

**Comment by code-devnull** [comment]
Hi buddy,
I am facing the issue when run this command as well. Can you share your solution?
