### ISSUE TITLE
When did mapLibre fork?

### ISSUE THREAD

**Issue by tir38** [maplibre/maplibre-gl-native#199]
What commit/version of original https://github.com/mapbox/mapbox-gl-native did MapLibre fork from? I'm having a hard time grepping what might be "missing" from MapLibre that Mapbox added post-forking.

**Comment by petr-pokorny-1** [comment]
@tir38 

from README:

> The mapbox-gl-native was forked from d60fd30 - mgbl 1.6.0, mapbox-gl-native-ios from a139216 and mapbox-gl-native-android from 4c12fb2

**Comment by tir38** [comment]
great thanks.
