### ISSUE TITLE
For Mobile SDKs, Create a Documentation website or GH-Pages

### ISSUE THREAD

**Issue by roblabs** [maplibre/maplibre-gl-native#20]
Starting a GitHub Project for _a Documentation web site for GL Native docs_ (similar to [maplibre/maplibre-gl-js-docs](https://github.com/maplibre/maplibre-gl-js-docs)).

Examples of how it could be designed:

* MapLibre.org/docs/android
* MapLibre.org/docs/ios

or,
* docs.maplibre.org/mobile/ios
* etc.

or, it could simply be hosted on the branch `gh-pages`

* maplibre.github.io/maplibre-gl-native/ios
* maplibre.github.io/maplibre-gl-native/android

Tasks

- [ ] Review existing docs and rebrand for MapLibre
- [ ] Setup hosting (determine web site architecture, `CNAME`, GH-pages, etc)
- [ ] Update GitHub Actions to publish based on a release

---

Notes on making docs

Android

* [GitHub Action](https://github.com/maplibre/maplibre-gl-native/blob/master/.github/workflows/android-release.yml#L114,L115)

* `make android-javadoc`

iOS

* [maplibre-gl-native/platform/ios/platform/ios/scripts/document.sh](https://github.com/maplibre/maplibre-gl-native/blob/62ab3e43407e450cb8215d67632117d381d9bbbb/platform/ios/platform/ios/scripts/document.sh#L36,L50)
* `make idocument`

![image](https://user-images.githubusercontent.com/118112/108248577-e88a8000-7108-11eb-8c7b-e3ae00d11c1a.png)

**Comment by matkoniecz** [comment]
Would it also cover updating links in README - https://github.com/maplibre/maplibre-gl-native/tree/master/platform/android#getting-started ? Or is it a different documentation?

**Comment by mohand1993** [comment]
isn't the documentation here https://docs.maptiler.com/maplibre-gl-native-android/ up-to-date?

**Comment by wipfli** [comment]
Oh nice we should build this :)

**Comment by wipfli** [comment]
I guess building the iOS docs only works on macos...

**Comment by mohand1993** [comment]
@wipfli Are there any plans to create a quickstart tutorial (e.g. anything similar to https://maplibre.org/maplibre-gl-js-docs/api/#quickstart)?

**Comment by mohand1993** [comment]
@wipfli I am afraid we cannot, as we are not that familiar with the library.
We kind of hoped we can find such tutorial that helps us adopting this maps solution in our apps, so we haven't started using the library yet.
