### ISSUE TITLE
3d terrain support

### ISSUE THREAD

**Issue by AAverin** [maplibre/maplibre-gl-native#223]
Is 3d terrain supported by gl-native?
Could be a stupid question, but does gl-native power gl-js or those work independently? I ask because 3D terrain seems to come to js https://github.com/maplibre/maplibre-gl-js/pull/165

**Comment by lseelenbinder** [comment]
@AAverin

They'd be entirely separate and separate implementations. There's almost no shared code (native is C++ with some native libraries and GL JS is JS). I'm not aware of anyone working on 3D terrain for native.

**Comment by paulsUsername** [comment]
This would be really great!

**Comment by wipfli** [comment]
I will close this for now. Feel free to continue discussing Terrain3D in #252
