### ISSUE TITLE
Failed to load tile 7/24/50=>7 for source my-vector-tiles: unknown pbf field type exception

### ISSUE THREAD

**Issue by cobra811** [maplibre/maplibre-gl-native#242]
E/Mbgl: {GLThread 96952}[Style]: Failed to load tile 7/24/50=>7 for source my-vector-tiles: unknown pbf field type exception
This error happens for the entire S3 bucket of vector tiles.

Does anyone know why this error is occurring? I'm hosting a tileset in a z/x/y folder structure on AWS S3. I've tried changing content-encoding to gzip and content-type to application/x-protobuf but this does not solve the issue.  Can it be a style issue? For example, a style layer I'm trying to use is not in the vector? Based on the error, I don't really know where to investigate further.

**Comment by brendan-ward** [comment]
How were your tiles generated?  Are you able to share a URL?  Does it work properly in other GL clients, e.g., maplibre-gl-js, mapbox-gl-js, etc?

From the message, it sounds like it could perhaps be an encoding error in the vector tiles, perhaps using a field (tag) value type that is not supported by the [specification](https://github.com/mapbox/vector-tile-spec/blob/master/2.1/vector_tile.proto#L17-L28)?

**Comment by roblabs** [comment]
@cobra811  — check the discussion on this thread https://github.com/mapbox/tippecanoe/issues/582#issuecomment-394169847 where the poster is discussing hosting on S3.  As a follow up to Brendan's notes:  check if your app can use other well known PBF's, or if your tiles can be _soft proofed_ using MapTiler or Tile Server GL.

**Comment by cobra811** [comment]
@roblabs Thank you for the link. I double checked the content-encoding on S3 and that was the problem, many of the tiles were not set as gzip. I think when I originally updated the metadata content-encoding on S3 it failed to complete the process (too many files).

**Comment by sobmortin** [comment]
Hello, I am having a similar problem now.  Can someone please advise further on how to set the content encoding on S3 for pbf files? Many thanks
