### ISSUE TITLE
Support building on Arm / Apple Silicon

### ISSUE THREAD

**Issue by birkskyum** [maplibre/maplibre-gl-native#255]
When running `cmake --build build` in the root of the repo, this error occurs:

```
clang: error: invalid arch name '-arch -isysroot'
```

**Comment by ntadej** [comment]
Not even sure what this does. I guess it build native node.js bindings. We should cleanup our build infrastructure as there are just too many ways how one can build stuff here 😊

**Comment by mharju** [comment]
There is a bug in the build system that drops the architecture env variable that is supposed to go there from the builds – basically you can just grep all the places you find that combination and replace it with `-arch arm64 -isysroot` to get it to compile again – worked for me at least.

**Comment by birkskyum** [comment]
@mharju , thank you for helping me out! I'm not exactly sure where to do this grep command still. When I search the codebase for `-arch -isysroot` I don't find it anywhere.

**Comment by birkskyum** [comment]
@mharju Most of the files compile, but near the end I see this:

```
Consolidate compiler generated dependencies of target mbgl-test-runner
[ 81%] Building CXX object CMakeFiles/mbgl-test-runner.dir/platform/default/src/mbgl/test/main.cpp.o
[ 81%] Linking CXX executable mbgl-test-runner
ld: warning: argument missing after -force_load
ld: file not found: -lmbgl-test
```

Does it look familiar to you?

**Comment by mharju** [comment]
> @mharju Most of the files compile, but near the end I see this:
> 
> ```
> Consolidate compiler generated dependencies of target mbgl-test-runner
> [ 81%] Building CXX object CMakeFiles/mbgl-test-runner.dir/platform/default/src/mbgl/test/main.cpp.o
> [ 81%] Linking CXX executable mbgl-test-runner
> ld: warning: argument missing after -force_load
> ld: file not found: -lmbgl-test
> ```
> 
> Does it look familiar to you?

Unfortunately no – but based on the error mbgl-test library did not seem to compile or was not added properly to libpath that it was looking it from? Should it be compiled and available...?

**Comment by wipfli** [comment]
There was a related discussion at https://github.com/maplibre/maplibre-gl-native/issues/4
