### ISSUE TITLE
iOS Crash: ThreadedSchedulerBase::makeSchedulerThread

### ISSUE THREAD

**Issue by racer1988** [maplibre/maplibre-gl-native#265]
Since we released the iOS app with SDK `19E239` we are getting costant crashes reported

```void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, mbgl::ThreadedSchedulerBase::makeSchedulerThread(unsigned long)::$_0> >(void*) + 436```

No issue with SDK `19C51`

Does somebody have a clue of what could be triggering this crash?

**Comment by atierian** [comment]
This is a different issue than https://github.com/maplibre/maplibre-gl-native/issues/268, correct?
Do you have any data around the crash, like affected iOS version and devices, that you can share?
Also a full stack trace would be very helpful diagnosing this.

**Comment by racer1988** [comment]
@atierian Yes It's a different crash.

I reported it with all info I got from Firebase.

However after some deeper investigation,  it seems to be that my app is crashing due to a issue in the Apple SDK when running code on Swift5.5 while compiled with Swift5.6.

The CPU usage spikes to 100% for too much time and the app gets killed.

What I think it's reported it's "kinda wrong"
It's not MapLibre the cause of the crash, but simply due to no resources available, the report and the MapLibre Thread are stuck on trying to create a new Thread.

We can close this Issue I'd say.

I just wanted to report for knowledge that a `makeSchedulerThread` crash probably means the client was not having any CPU resource available.

**Comment by atierian** [comment]
Thanks for the follow up. I'll close this issue based on the information you provided. If you encounter this crash again where it can't be attributed to differing Swift versions, please open a new issue or comment on this one and I'll reopen to take a closer look.
