### ISSUE TITLE
[android] Bintray alternative: Packages for Android MapLibre distribution

### ISSUE THREAD

**Issue by petr-pokorny-1** [maplibre/maplibre-gl-native#27]
Bintray will be turn off May 1st, 2021

**Comment by moopat** [comment]
Got reminded of this when my builds started failing during [today's brown-out session](https://status.bintray.com/incidents/x1dvhtdqkcnx). 

Can this be fixed before May?

**Comment by petr-pokorny-1** [comment]
@moopat I have copied packages from Bintray to [Maven Central.](https://search.maven.org/artifact/org.maplibre.gl/android-sdk)

A quick test in a project consuming MapLibre through Maven shows that all what is needed is to remove `jcenter()` and add `mavenCentral()' in build.gradle repositories list.

We are working on gradle deploy script migration so that new releases are deployed to Maven Central, but it will take a while. [It looks like jFrog will keep JCenter running until Feb 1 2022.](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)

**Comment by carlonzo** [comment]
@petr-pokorny-1 any plans or solutions to remove `mapbox-android-accounts` dependency or move it to mavencentral? 
https://github.com/maplibre/maplibre-gl-native/blob/452537d0caddff93a55a97e0127a9ff09f8d5080/platform/android/gradle/dependencies.gradle#L46

thats the only dependency from maplibre that still requires jcenter to use maplibre

**Comment by petr-pokorny-1** [comment]
> mapbox-android-account



> @petr-pokorny-1 any plans or solutions to remove `mapbox-android-accounts` dependency or move it to mavencentral?
> https://github.com/maplibre/maplibre-gl-native/blob/452537d0caddff93a55a97e0127a9ff09f8d5080/platform/android/gradle/dependencies.gradle#L46
> 
> thats the only dependency from maplibre that still requires jcenter to use maplibre

@carlonzo yes, it was removed - now it is ready for review along with many other changes in #90
