### ISSUE TITLE
[Android] Location permission on Android 12

### ISSUE THREAD

**Issue by daweiser** [maplibre/maplibre-gl-native#275]
When setting the targetSdk to 31, Android requires to also request android.permission.ACCESS_COARSE_LOCATION when requesting android.permission.ACCESS_FINE_LOCATION. The coarse location permission is currently missing in AndroidManifest.xml

See: https://developer.android.com/training/location/permissions#approximate-request

This also makes this lint check to fail: https://googlesamples.github.io/android-custom-lint-rules/checks/CoarseFineLocation.md.html

**Comment by louwers** [comment]
This is fixed by now. :slightly_smiling_face: 

https://github.com/maplibre/maplibre-gl-native/blob/33cb3ae39bbb67608d4ec9088740b12f6d798219/platform/android/MapboxGLAndroidSDK/src/main/AndroidManifest.xml#L13
