### ISSUE TITLE
Highway shield (glyph?) text not centered.

### ISSUE THREAD

**Issue by acalcutt** [maplibre/maplibre-gl-native#279]
Hi Everyone,

I have been trying to make a maplibre version of Tileserver-GL with the newly revived node version of maplibre-gl-native which is up on github here ( https://github.com/acalcutt/tileserver-gl )

For the most page it all seems to be working, however on the "raster" pages which rely on maplibre-gl-native in the background, I notice the text for highway shields is not getting centered. like this
![shields_after](https://user-images.githubusercontent.com/3792408/165636910-37b00ace-4d4e-4727-a831-9bf03ed91c0c.png)

With the mapbox-gl-native used before, it looks correct like this
![shields_before](https://user-images.githubusercontent.com/3792408/165637066-00f147e4-2d82-47a0-a2e9-e1e47d9ab3a0.png)

I brought this up on slack and another user said they had the same issue with the shields and had to move to mapbox-gl-native to fix the issue. since someone else confirmed this issues, i figured I would make a post here.

I am using this with this style, which is based on OMT Bright style
https://github.com/acalcutt/wifidb-tileserver-gl/blob/master/tileserver-gl/styles/WDB_OSM/style.json#L4724-L4773

here is a live example
https://tiles.wifidb.net/styles/WDB_OSM/?raster#11/42.2143/-71.8190

**Comment by lseelenbinder** [comment]
Thanks for making this ticket @acalcutt. I'm that other user, and in fact I had issues with _all_ label positioning. For example, city labels that should have been top-left aligned where bottom-left aligned.

**Comment by acalcutt** [comment]
Thanks @lseelenbinder for confirming here. 

I spent a little bit of time testing and did confirm just changing back to mapbox-gl-native did make the labels appear normal again. I did a bit of comparing beetween mapbox 5.0.2 and the current maplibre, but there are many changes since that release so nothing stuck out.

I was mainly looking around symbol layout based on these previous mapbox shield text issues
https://github.com/mapbox/mapbox-gl-native/issues/5683
https://github.com/mapbox/mapbox-gl-native/issues/9395

**Comment by acalcutt** [comment]
I've uploaded a test style and a mbtiles file of massachusetts which includes shields at ( https://github.com/acalcutt/tileserver-gl/releases/download/test_data/test_data_massachusetts.zip )

This is an example of using in the docker version my tileserver-gl
1.) git clone https://github.com/acalcutt/tileserver-gl.git
2.) cd tileserver-gl
3.) docker build --no-cache -t test1 .
4.) wget https://github.com/acalcutt/tileserver-gl/releases/download/test_data/test_data_massachusetts.zip
5.) unzip test_data_massachusetts.zip
6.) docker run -v $(pwd):/data -p 8080:80 test1
7.) Browse to 127.0.0.1:8080 and click 'raster' under the WDB_OSM style (eg. http://127.0.0.1:8080/styles/wdb-osm/?raster#10/42.2595/-71.9028 ) .
8.) see shields and text not looking correct
9.) Ctrl+C in the docker window to kill tileserver-gl

**Comment by rmyhal** [comment]
@acalcutt the issue was introduced in [this PR](https://github.com/maplibre/maplibre-gl-native/pull/270)

cc @ntadej , could you please help us?

**Comment by acalcutt** [comment]
I can confirm, I tested reverting https://github.com/maplibre/maplibre-gl-native/pull/270 in @acalcutt/maplibre-gl-native@5.0.15 and made manually changed my local tileserver-gl to use that release and it seems like it worked

![image](https://user-images.githubusercontent.com/3792408/168686300-df518786-f73d-4169-b7ad-d2d10ff0f97b.png)

**Comment by acalcutt** [comment]
While it does fix the shields, there is still a bit of something going on with the text, for example. 

With 
docker run --rm -it -v $(pwd):/data -p 8080:80 wifidb/tileserver-gl
![maplibre](https://user-images.githubusercontent.com/3792408/168706029-5549e1cc-a24c-4454-8fe1-7622589bb990.png)

With
docker run --rm -it -v $(pwd):/data -p 8080:80 maptiler/tileserver-gl
![mapbox](https://user-images.githubusercontent.com/3792408/168706019-aa1d74db-b7b4-4f91-9ca6-09218503703b.png)

This should probably be a separate issue though.

**Comment by ntadej** [comment]
Is this node bindings only? As I see no issues with text in apps.

Will look into shields.

**Comment by rmyhal** [comment]
> Is this node bindings only? As I see no issues with text in apps.
> 
> Will look into shields.

I found the problem. [Here](https://github.com/maplibre/maplibre-gl-native/pull/270/files#diff-d57cd3143ace69af2f7ae79a917ac1328acc7543ae8a2a15f58b4635b86f1b91R148) you made a typo during adding `static_cast` and misplaced brackets. The fix looks like this:
`shiftY = (-verticalAlign * static_cast<float>(lineCount) + 0.5) * lineHeight;`

**Comment by acalcutt** [comment]
I had seen this when researching the shield issue https://github.com/mapbox/mapbox-gl-native/pull/15880 which at least sounds similar to the label issue i am seeing. though when i looked at the maplibre code it looked like some of thqt fix made it over already.

Not sure if this is a node issue since id didnt happen (or at least didn't happen as much) with the mapbox version (as you can see from the screenshot of the maptiler version

**Comment by acalcutt** [comment]
I can confirm the line [rmyhal](https://github.com/rmyhal) mentioned seems to work. I put back #270 and applied that line fix and the shields look correct.

**Comment by acalcutt** [comment]
I could put in a PR with that fix, unless @rmyhal wants to put it in.

**Comment by rmyhal** [comment]
thanks @acalcutt !
I can fill a PR soon

**Comment by rmyhal** [comment]
@acalcutt 

https://github.com/maplibre/maplibre-gl-native/pull/285
