### ISSUE TITLE
[android] Move Mapbox Android plugins to MapLibre

### ISSUE THREAD

**Issue by petr-pokorny-1** [maplibre/maplibre-gl-native#28]
Create fork of MapBox android plugin and move it under MapLibre
https://github.com/mapbox/mapbox-plugins-android

**Comment by m0nac0** [comment]
This will probably be necessary for #41, since https://github.com/tobrun/flutter-mapbox-gl relies on 3 of these plugins.
Are there already any plans for this?

**Comment by petr-pokorny-1** [comment]
We will be creating new release this week and then make a plan for next one. So perhaps we could include android plugin migration in the next release. Another related issue is https://github.com/maplibre/maplibre-gl-native/issues/27
