### ISSUE TITLE
X_GLXCreatePbuffer error while running the test suite

### ISSUE THREAD

**Issue by dwoznicki** [maplibre/maplibre-gl-native#282]
After building and running `mbgl-test-runner` on my Ubuntu 20.04 machine, I get the following error:

```
19:16:29 ❯ ./mbgl-test-runner
[==========] Running 888 tests from 114 test suites.

---------- snip to ignore passing tests ----------

[----------] 28 tests from Annotations
[ RUN      ] Annotations.SymbolAnnotation
X Error of failed request:  BadAlloc (insufficient resources for operation)
  Major opcode of failed request:  153 (GLX)
  Minor opcode of failed request:  27 (X_GLXCreatePbuffer)
  Serial number of failed request:  23
  Current serial number in output stream:  26
```

[Research has suggested](https://www.mail-archive.com/virtualgl-users@googlegroups.com/msg00342.html) that this might be an issue with my AMD graphics card, but I'm not familiar enough with this space to really be sure.

Note that I don't run into this issue when executing with `xvfb-run -a ./mbgl-test-runner` (though I do eventually hit a different test failure).

Does anyone have any ideas on how to solve this?

**Comment by lseelenbinder** [comment]
Hey @dwoznicki. You have to execute the tests in the context of a `DISPLAY` (which is what `xvfb-run` gives you by creating a virtual framebuffer), so unless the tests were already able to access a X display, this is expected.

Were you running them from within a desktop environment or is it just a server context? You can normally see if you already have access to a display by checking the `DISPLAY` environment variable before running the tests. If you were, for example, to run `xvfb-run /bin/bash -c "echo $DISPLAY"` it would be set to the xvfb managed display.

**Comment by dwoznicki** [comment]
Thanks for the reply @lseelenbinder. I am running this from a desktop with access to a display.

```
19:21:49 ❯ echo $DISPLAY
:1
```

My display appears to be recognized by GLX as well.

```
10:17:45 ❯ glxinfo -B
name of display: :1
display: :1  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: AMD (0x1002)
    Device: AMD OLAND (DRM 2.50.0, 5.16.19-76051619-generic, LLVM 12.0.0) (0x6613)
    Version: 21.2.2
    Accelerated: yes
    Video memory: 2048MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 4.5
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 1835 MB, largest block: 1835 MB
    VBO free aux. memory - total: 1953 MB, largest block: 1953 MB
    Texture free memory - total: 1835 MB, largest block: 1835 MB
    Texture free aux. memory - total: 1953 MB, largest block: 1953 MB
    Renderbuffer free memory - total: 1835 MB, largest block: 1835 MB
    Renderbuffer free aux. memory - total: 1953 MB, largest block: 1953 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 2048 MB
    Total available memory: 4091 MB
    Currently available dedicated video memory: 1835 MB
OpenGL vendor string: AMD
OpenGL renderer string: AMD OLAND (DRM 2.50.0, 5.16.19-76051619-generic, LLVM 12.0.0)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 21.2.2
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.5 (Compatibility Profile) Mesa 21.2.2
OpenGL shading language version string: 4.50
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 21.2.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

I'll also note that I get the same display value when I run with xvfb. Not sure what to make of that.

```
10:19:46 ❯ xvfb-run /bin/bash -c "echo $DISPLAY"
:1
```

**Comment by dwoznicki** [comment]
I now firmly believe this to be an issue with my AMD GPU. I successfully built and ran the test suite on a different desktop with an integrated Intel graphics card.

**Comment by lseelenbinder** [comment]
Thanks for following up @dwoznicki! Best of luck getting it to work. 😄
