### ISSUE TITLE
Labels getting clipped in tile mode (node version)

### ISSUE THREAD

**Issue by acalcutt** [maplibre/maplibre-gl-native#284]
I mentioned this issue in https://github.com/maplibre/maplibre-gl-native/issues/279 , but did not want to pollute that thread with an unrelated problem.

In my testing of the node version of maplibre-gl-native in my branch of [tileserver-gl](https://github.com/acalcutt/tileserver-gl/) I have noticed labels getting clipped more than in the mapbox-gl-native version.

For example, in the maplibre-gl-native version it is consistently cutting off labels all over the place like this
![maplibre](https://user-images.githubusercontent.com/3792408/169196629-feada2a1-0579-49a1-82bf-cdf879a0334f.png)

Where in the maptiler version using mapbox-gl-native v5.02, does not have this issue 
![mapbox](https://user-images.githubusercontent.com/3792408/169196781-45d50301-de5c-409f-ae87-c1d48200e3be.png)

Looking at several similar threads I found these related mapbox issues
https://github.com/mapbox/mapbox-gl-native/issues/15805
https://github.com/mapbox/mapbox-gl-native/issues/14011
https://github.com/mapbox/mapbox-gl-native/pull/15880
The first article in this list mentions this was improved in v5.0.2, which I did find the change they mentioned here https://github.com/mapbox/mapbox-gl-native/commit/d500b67d4a73ccbfbc59b78a3277538b01d1cb5e. the padding was increased when in tile mode to help the labels to help with the trimming (a change which still exists, slightly rewritten). Also, in tileserver-gl they added the code to use tile mode here https://github.com/maptiler/tileserver-gl/commit/5048388d1fbfce3f983e6ee0338bafaa90e947ce

Looking though the related code in https://github.com/maplibre/maplibre-gl-native/blob/main/src/mbgl/text/collision_index.cpp#L26-L50 it seems like the changes that added padding in tile mode are still there and looking in my tileserver-gl code the tile mode option is still set ( https://github.com/acalcutt/tileserver-gl/blob/main/src/serve_rendered.js#L574 )

From this, to me, it seems like it should be showing the labels correct like in the second screenshot, but for some reason it is not. 

One idea I had is maybe it is ignoring the tile mode switch? I'm guessing that would be [this code](https://github.com/maplibre/maplibre-gl-native/blob/main/platform/node/src/node_map.cpp#L1403-L1409) in the node binding code?

Does anyone have any other idea or tips that could help? I am told there is no issue with labels in the android version, which Is why I was thinking something with the node mode switch.

**Comment by wipfli** [comment]
Thanks for reporting this @acalcutt Is there a way to reproduce this cropping problem with the linux native renderer and the demotiles?

**Comment by acalcutt** [comment]
Is the any information on using the linux native renderer? like at least switches mbgl-render needs?

Basically I would want to try an recreate this view, where it trims "United States"
https://tiles.wifidb.net/styles/demotiles/?raster#6/39.470/-98.701
![image](https://user-images.githubusercontent.com/3792408/172020546-00099f9f-cf09-469b-ae6a-bb971c114b48.png)

**Comment by acalcutt** [comment]
I tried various zoom levels, like
`xvfb-run -a ./mbgl-render -z 6 -y 39.436 -x -101 --style style.json --output out6.png`

but I wasn't able to see any clipping. I always assumed this was where the label was at the edge of the tile. so I think to test this you would need two tiles that are side by side where the label gets clipped off. also, I'm not sure this mbgl-render can do tile mode, where it overdraws a bit to help with the labels.

**Comment by acalcutt** [comment]
I've made a application to test this issue here
https://github.com/acalcutt/maplibre-label-clipping-test
( Note, this is made to be run in node 10 to be compatible with the mapbox-gl-native release )

Test 1 - With maplibre-gl-native
git clone https://github.com/acalcutt/maplibre-label-clipping-test.git
cd maplibre-label-clipping-test
npm i 
xvfb-run -a node index.js
2 images are generate, which look like this
![ml_1](https://user-images.githubusercontent.com/3792408/172034135-c5b02a47-e0c5-4f10-b558-3b8fdf5a536b.png)
![ml_2](https://user-images.githubusercontent.com/3792408/172034140-9332b4b4-76e4-471e-b229-50685ffd4fcc.png)

Test 2 - With mapbox-gl-native
Edit index.js.
uncomment line 8 (let mbgl = require('@mapbox/mapbox-gl-native');)
comment line 9 (//let mbgl = require('@acalcutt/maplibre-gl-native');)
xvfb-run -a node index.js
2 images are generate, which look like this
![mb_1](https://user-images.githubusercontent.com/3792408/172034244-f99f31a5-22b6-44fc-a5af-8264d07d96f8.png)
![mb_2](https://user-images.githubusercontent.com/3792408/172034251-a7565096-53c4-4be4-800e-dd04e22e0c4d.png)


Compare the maplibre version to the mapbox version. In the maplinre version, the "North" in "North Adams", which is right on the edge, is missing. However in the mapbox version, it is there as expected.

**Comment by wipfli** [comment]
I also tried with
```
wget https://raw.githubusercontent.com/maplibre/demotiles/gh-pages/style.json
./build/bin/mbgl-render --style style.json --output out.png --zoom 6 --lat 39.470 --lon -103
```
but always got correctly clipped labels...

**Comment by wipfli** [comment]
Hm interesting, is the diff between mapbox-gl-native and maplibre-gl-native large? When was their last common commit?

**Comment by acalcutt** [comment]
The diff is pretty large between the mapbox last version.

My assumption right now is this is related to the mode switch. If I go remove this line (mode: 'tile',) https://github.com/acalcutt/maplibre-label-clipping-test/
![1](https://user-images.githubusercontent.com/3792408/172045316-ec42e110-0dbb-484d-8084-ef2ddaf2e953.png)
![2](https://user-images.githubusercontent.com/3792408/172045318-1589ab6a-685d-4d6b-ad5f-10556c67f59e.png)
blob/main/index.js#L147 , with the mapbox version, it produces the same output as maplibre.

The code for tile mode has been refactored a bit, since mapbox 5.0.2...maybe there was some mistake with that
https://github.com/maplibre/maplibre-gl-native/blob/main/src/mbgl/text/collision_index.cpp#L26-L50

**Comment by acalcutt** [comment]
I've done a few thing to try and track this down...non successful so far.

1.) I tried setting [viewportPaddingDefault](https://github.com/maplibre/maplibre-gl-native/blob/main/src/mbgl/text/collision_index.cpp#L26)  to 1024, like is supposed to happen in tile mode to see if maybe the tile mode switch was not working. However even at 1024 the label clipping still occurred.

2.) I tried reverting back to the first maplibre node release in  cfcbc62fadd72224aac242c516a5a86510a1d102 , but the issue seemed to be happening in that release also

3.) I tried going back really far to a mapboc release that mentioned tile mode b84449e35fd38788fbbbe9c67e338e8317cd7150 , but unfortunately I couldn't get it to build. I used the instruction for that release, but I assume in needs an older GCC since I was getting syntax errors.

**Comment by wipfli** [comment]
Maybe you can install it from a local folder https://stackoverflow.com/questions/8088795/installing-a-local-module-using-npm

**Comment by pbnsilva** [comment]
Have you made any progress @acalcutt ? I'm seeing a fair amount of clipping and overlaps.

**Comment by acalcutt** [comment]
Unfortunately I haven't figured anything else. I haven't had much time to look though since my real job has kept me really busy this month.

My last test leads me to believe maybe it isn't tile mode padding like I was originally thinking.

**Comment by acalcutt** [comment]
I updated [@acalcutt/maplibre-gl-native@5.0.21](https://www.npmjs.com/package/@acalcutt/maplibre-gl-native) to include these [render fixes](https://github.com/maplibre/maplibre-gl-native/pull/351). unfortunately it doesn't look like they fixed the issue here.

I was hopeful since the fixes were in the same files... but somewhat expected since I had tried to revert https://github.com/maplibre/maplibre-gl-native/pull/270 before and it didn't fix this issue.

**Comment by wipfli** [comment]
Maybe also look in the ignored tests.

If I run
```
cmake . -B build -G Ninja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10
cmake --build build -j $(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null)
./build/mbgl-render-test-runner --manifestPath metrics/linux-clang8-release-style.json &> render-test.log
sed -i 's/\x1b\[[0-9;]*m//g' render-test.log
cat render-test.log | grep "* ignore"
```

I get these ignored tests:

``` 
* ignore render-tests/symbol-cross-fade/chinese (https://github.com/mapbox/mapbox-gl-native/issues/10619)
* ignore render-tests/real-world/bangkok (https://github.com/mapbox/mapbox-gl-native/issues/10412)
* ignore render-tests/real-world/sanfrancisco (https://github.com/mapbox/mapbox-gl-native/issues/10412)
* ignore render-tests/real-world/chicago (https://github.com/mapbox/mapbox-gl-native/issues/10412)
* ignore render-tests/tilejson-bounds/overwrite-bounds (started failing after https://github.com/mapbox/mapbox-gl-native/pull/16091)
* ignore render-tests/fill-extrusion-vertical-gradient/default (https://github.com/mapbox/mapbox-gl-js/pull/9202)
* ignore render-tests/fill-extrusion-vertical-gradient/false (https://github.com/mapbox/mapbox-gl-js/pull/9202)
* ignore render-tests/mixed-zoom/z10-z11 (https://github.com/mapbox/mapbox-gl-native/issues/10397)
* ignore render-tests/projection/perspective (https://github.com/mapbox/mapbox-gl-js/pull/9202)
* ignore render-tests/runtime-styling/set-style-glyphs (started failing after https://github.com/mapbox/mapbox-gl-native/pull/16091)
* ignore render-tests/fill-extrusion-geometry/linestring (https://github.com/mapbox/mapbox-gl-native/pull/14240)
* ignore render-tests/regressions/mapbox-gl-js#6806 (pending https://github.com/mapbox/mapbox-gl-js/pull/6812)
* ignore render-tests/regressions/mapbox-gl-js#5740 (https://github.com/mapbox/mapbox-gl-native/issues/10619)
* ignore render-tests/regressions/mapbox-gl-js#6706 (https://github.com/mapbox/mapbox-gl-native/issues/10619)
* ignore render-tests/regressions/mapbox-gl-js#7271 (https://github.com/mapbox/mapbox-gl-native/issues/12888)
* ignore render-tests/regressions/mapbox-gl-js#2762 (https://github.com/mapbox/mapbox-gl-native/issues/10619)
* ignore render-tests/regressions/mapbox-gl-js#5642 (Failing with mbgl-render-test)
* ignore render-tests/regressions/mapbox-gl-native#7357 (https://github.com/mapbox/mapbox-gl-native/issues/7357)
* ignore render-tests/regressions/mapbox-gl-js#5982 (https://github.com/mapbox/mapbox-gl-native/issues/10619)
* ignore render-tests/regressions/mapbox-gl-js#2769 (https://github.com/mapbox/mapbox-gl-native/issues/10619)
* ignore render-tests/regressions/mapbox-gl-js#7066 (Failing with mbgl-render-test)
* ignore render-tests/regressions/mapbox-gl-js#2467 (https://github.com/mapbox/mapbox-gl-native/issues/10619)
* ignore render-tests/symbol-sort-key/placement-tile-boundary-right-then-left (https://github.com/mapbox/mapbox-gl-js/pull/9054)
* ignore render-tests/text-max-width/zero-width-point-placement (https://github.com/mapbox/mapbox-gl-native/issues/15648)
* ignore render-tests/extent/1024-circle (needs investigation)
* ignore render-tests/extent/1024-symbol (https://github.com/mapbox/mapbox-gl-js/pull/9202)
* ignore render-tests/icon-text-fit/text-variable-anchor-overlap (https://github.com/mapbox/mapbox-gl-native/issues/15809)
* ignore render-tests/zoomed-fill/negative-zoom (https://github.com/mapbox/mapbox-gl-native/issues/16019)
* ignore render-tests/geojson/inline-linestring-fill (current behavior is arbitrary)
* ignore render-tests/debug/padding/ease-to-no-distort (https://github.com/mapbox/mapbox-gl-native/issues/16212)
* ignore render-tests/debug/padding/set-padding (https://github.com/mapbox/mapbox-gl-native/issues/16212)
* ignore render-tests/debug/padding/ease-to-right-distort (https://github.com/mapbox/mapbox-gl-native/issues/16212)
* ignore render-tests/debug/padding/ease-to-left-distort (https://github.com/mapbox/mapbox-gl-native/issues/16212)
* ignore render-tests/debug/padding/ease-to-btm-distort (https://github.com/mapbox/mapbox-gl-native/issues/16212)
* ignore render-tests/debug/padding/ease-to-top-distort (https://github.com/mapbox/mapbox-gl-native/issues/16212)
* ignore render-tests/debug/collision (https://github.com/mapbox/mapbox-gl-native/issues/3841)
* ignore render-tests/debug/tile-overscaled (https://github.com/mapbox/mapbox-gl-native/issues/3841)
* ignore render-tests/debug/overdraw (https://github.com/mapbox/mapbox-gl-native/issues/15638)
* ignore render-tests/debug/raster (https://github.com/mapbox/mapbox-gl-native/issues/15510)
* ignore render-tests/debug/tile (https://github.com/mapbox/mapbox-gl-native/issues/3841)
* ignore render-tests/line-pattern/opacity (Flaky on Linux: https://github.com/mapbox/mapbox-gl-native/issues/15320)
* ignore render-tests/line-pattern/with-dasharray (https://github.com/mapbox/mapbox-gl-js/pull/9189)
* ignore render-tests/fill-opacity/zoom-and-property-function-pattern (Flaky on Linux: https://github.com/mapbox/mapbox-gl-native/issues/15322)
* ignore render-tests/raster-masking/overlapping-zoom (https://github.com/mapbox/mapbox-gl-native/issues/10195)
* ignore render-tests/text-size/nan (https://github.com/mapbox/mapbox-gl-native/issues/16020)
* ignore render-tests/background-color/colorSpace-hcl (needs issue)
* ignore render-tests/background-color/transition (https://github.com/mapbox/mapbox-gl-native/issues/10619)
* ignore render-tests/line-translate/literal (Flaky on Linux: https://github.com/mapbox/mapbox-gl-native/issues/14859)
* ignore render-tests/tile-mode/streets-v11 (ignored due to flaky metrics results)
* ignore render-tests/fill-pattern/update-feature-state (https://github.com/mapbox/mapbox-gl-native/issues/15895)
* ignore render-tests/fill-pattern/literal (Flaky on Linux: https://github.com/mapbox/mapbox-gl-native/issues/14423)
* ignore render-tests/fill-pattern/zoomed (Flaky on Linux: https://github.com/mapbox/mapbox-gl-native/issues/14768)
* ignore render-tests/fill-pattern/opacity (Flaky on Linux: https://github.com/mapbox/mapbox-gl-native/issues/14870)
* ignore render-tests/fill-extrusion-translate/default (https://github.com/mapbox/mapbox-gl-js/pull/9202)
* ignore render-tests/fill-extrusion-pattern/feature-expression (https://github.com/mapbox/mapbox-gl-js/issues/3327)
* ignore render-tests/fill-extrusion-pattern/literal (https://github.com/mapbox/mapbox-gl-js/issues/3327)
* ignore render-tests/fill-extrusion-pattern/opacity (https://github.com/mapbox/mapbox-gl-js/issues/3327)
* ignore render-tests/fill-extrusion-pattern/function (https://github.com/mapbox/mapbox-gl-js/issues/3327)
* ignore render-tests/fill-extrusion-pattern/function-2 (https://github.com/mapbox/mapbox-gl-js/issues/3327)
* ignore render-tests/fill-extrusion-pattern/tile-buffer (https://github.com/mapbox/mapbox-gl-js/issues/3327)
* ignore render-tests/fill-extrusion-pattern/@2x (https://github.com/mapbox/mapbox-gl-js/issues/3327)
* ignore render-tests/feature-state/promote-id-fill-extrusion (https://github.com/mapbox/mapbox-gl-js/pull/9202)
* ignore render-tests/feature-state/promote-id-line (https://github.com/mapbox/mapbox-gl-js/pull/9202)
* ignore render-tests/feature-state/promote-id-fill (https://github.com/mapbox/mapbox-gl-js/pull/9202)
* ignore render-tests/feature-state/promote-id-circle (https://github.com/mapbox/mapbox-gl-js/pull/9202)
* ignore render-tests/feature-state/promote-id-symbol (https://github.com/mapbox/mapbox-gl-js/pull/9202)
* ignore render-tests/fill-extrusion-base/property-function (https://github.com/mapbox/mapbox-gl-js/pull/9202)
* ignore render-tests/fill-extrusion-base/zoom-and-property-function (https://github.com/mapbox/mapbox-gl-js/pull/9202)
* ignore render-tests/collator/default (Some test platforms don't resolve 'en' locale)
* ignore render-tests/collator/resolved-locale (Some test platforms don't resolve 'en' locale)
* ignore render-tests/fill-extrusion-opacity/default (https://github.com/mapbox/mapbox-gl-js/pull/9202)
* ignore render-tests/fill-extrusion-opacity/literal (https://github.com/mapbox/mapbox-gl-js/pull/9202)
* ignore render-tests/fill-extrusion-opacity/function (https://github.com/mapbox/mapbox-gl-js/pull/9202)
* ignore query-tests/regressions/mapbox-gl-js#7883 (https://github.com/mapbox/mapbox-gl-native/issues/14585)
* ignore query-tests/regressions/mapbox-gl-js#8999 (https://github.com/mapbox/mapbox-gl-js/pull/9138)
* ignore query-tests/fill-translate/multiple-layers (https://github.com/mapbox/mapbox-gl-native/issues/12701)
* ignore query-tests/fill-extrusion/sort-rotated (https://github.com/mapbox/mapbox-gl-native/issues/13139)
* ignore query-tests/fill-extrusion/sort (https://github.com/mapbox/mapbox-gl-native/issues/13139)
* ignore query-tests/fill-extrusion/top-in (https://github.com/mapbox/mapbox-gl-native/issues/13139)
* ignore query-tests/fill-extrusion/sort-concave-outer (https://github.com/mapbox/mapbox-gl-native/issues/13139)
* ignore query-tests/fill-extrusion/box-in (https://github.com/mapbox/mapbox-gl-native/issues/13139)
* ignore query-tests/fill-extrusion/sort-concave-inner (https://github.com/mapbox/mapbox-gl-native/issues/13139)
* ignore query-tests/fill-extrusion/side-in (https://github.com/mapbox/mapbox-gl-native/issues/13139)
* ignore query-tests/fill-extrusion/base-in (https://github.com/mapbox/mapbox-gl-native/issues/13139)
* ignore query-tests/geometry/polygon (needs investigation)
* ignore query-tests/geometry/multipolygon (needs investigation)
* ignore query-tests/geometry/multilinestring (needs investigation)
* ignore query-tests/evaluated/line-width (Port https://github.com/mapbox/mapbox-gl-js/pull/9198)
* ignore query-tests/fill-extrusion-translate/multiple-layers (https://github.com/mapbox/mapbox-gl-native/issues/12701)
```

**Comment by acalcutt** [comment]
I think I may have figure this out, but I am still testing to be sure.

For some reason in platform/node/src/node_map.cpp , the map "withMapMode" was hardcoded to "mbgl::MapMode::Static" and not using the "mode" variable
[L1424](https://github.com/maplibre/maplibre-gl-native/blob/main/platform/node/src/node_map.cpp#L1424) and [L645](https://github.com/maplibre/maplibre-gl-native/blob/main/platform/node/src/node_map.cpp#L645)

**Comment by acalcutt** [comment]
It worked! So far I have tested in my [tileserver-gl ](https://github.com/acalcutt/tileserver-gl) for and in the [label clipping test ](https://github.com/acalcutt/maplibre-label-clipping-test)above and it seems like it is fixed

This should be fixed in my npm package 
"@acalcutt/maplibre-gl-native": "5.0.25

This is what the two images from my label test look like now, no longer clipping labels
![1](https://user-images.githubusercontent.com/3792408/187050436-4ad5028f-5166-4d34-895b-01f5e87a27af.png)

**Comment by wipfli** [comment]
Really nice! Do you know if we can run the render test via the node platform?

**Comment by birkskyum** [comment]
Fixed by #415

**Comment by acalcutt** [comment]
@wipfli unfortunately I am not aware of how to run the render tests for node, or if there are any.

**Comment by acalcutt** [comment]
@wipfli 

To do the basic tests the build does in linux, it would be something like ubuntu 20.04
```
install prereqs from https://github.com/acalcutt/maplibre-gl-native/tree/main/platform/linux
git clone --recurse-submodules https://github.com/maplibre/maplibre-gl-native.git
npm ci --ignore-scripts
cmake . -B build -G Ninja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10
cmake --build build -j $(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null)
xvfb-run --auto-servernum npm test
```

however, looking in the package.json there are some other tests that didn't seem to work for me on my test vm
```
    "test-memory": "node --expose-gc platform/node/test/memory.test.js",
    "test-expressions": "node -r esm platform/node/test/expression.test.js",
    "test-render": "node -r esm platform/node/test/render.test.js",
    "test-query": "node -r esm platform/node/test/query.test.js",
```

**Comment by wipfli** [comment]
Ah interesting. The render test fixtures are indeed in the maplibre-gl-js submodule. Maybe even the test harness from GL JS is used for node?
