### ISSUE TITLE
Post C++ 17 clean-up

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-native#335]
If we should migrate the codebase to C++ 17, then we should clean-up some things. This issue is to track where we need to clean-up stuff.

**Comment by wipfli** [comment]
`#if __cplusplus >= 201703L` in `include/mbgl/actor/actor_ref.hpp`

**Comment by louwers** [comment]
I'm closing this as done.

If something else comes to mind that needs updating we will create separate tickets for it.
