### ISSUE TITLE
Gradle warning on Android builds

### ISSUE THREAD

**Issue by roblabs** [maplibre/maplibre-gl-native#336]
When building MapLibre for Android, there is a warning from the Gradle build.  It's not clear if upgrading to Gradle 7.0 will benefit MapLibre, but this may need maintenance in the future.

- [ ] Need to instrument a Gradle build with the recommended `--warning-mode all` to understand the root issue & deprecation warnings.

---

> Deprecated Gradle features were used in this build, making it incompatible with **Gradle 7.0**.
Use '`--warning-mode all`' to show the individual deprecation warnings.
See https://docs.gradle.org/6.4.1/userguide/command_line_interface.html#sec:command_line_warnings

---

- [ ] `ANDROID_NDK_HOME` warning

> WARNING: Support for `ANDROID_NDK_HOME` is deprecated and will be removed in the future. Use android.ndkVersion in build.gradle instead.

**Comment by birkskyum** [comment]
Related to #483

**Comment by birkskyum** [comment]
Closed by #611
