### ISSUE TITLE
Launch Issue with macOS Ventura + Xcode 14 + iOS 16 Simulator

### ISSUE THREAD

**Issue by roblabs** [maplibre/maplibre-gl-native#337]
Results from building MapLibre for iOS on macOS Ventura/Xcode 14 & inspired by a comment from [@username0x0a](https://github.com/username0x0a),  (🎩tip).

> *with Xcode 14 & iOS 16 Simulator, I'm getting an instant crash on launch*.  See details:  https://github.com/maplibre/maplibre-gl-native/issues/268#issuecomment-1149262031

---

As of now, I only have macOS Ventura running on a M1.  This issue would need to be verified on `x86_64`.

```bash
sw_vers
# ProductName:	macOS
# ProductVersion:	13.0
# BuildVersion:	22A5266r

uname -a
# Darwin m1.local 22.0.0 Darwin Kernel Version 22.0.0: Tue May 24 20:30:32 PDT 2022; 
# root:xnu-8792.0.50.111.3~5/RELEASE_ARM64_T8103 arm64

xcodebuild -version
# Xcode 14.0
# Build version 14A5228q
```

---

*Xcode 14 + iOS 16 Simulator*

![image](https://user-images.githubusercontent.com/118112/174410775-a7ca26ff-d0dc-4d79-b434-04515e165eac.png)

---

*Xcode 14 + iOS 16 Simulator has several deprecations*

![image](https://user-images.githubusercontent.com/118112/174411152-b6d6088f-92fe-4fe1-a377-9d4c465a3eac.png)

**Comment by roblabs** [comment]
An update on testing MapLibre for iOS with latest macOS Ventura (13.0 Beta (22A5295i)) on Apple Silicon (M1 Mac).

- [x]  The instant crash found [earlier](https://github.com/maplibre/maplibre-gl-native/issues/268#issuecomment-1149262031) is now fixed.
- [x] The C++ deprecations seem to have gone away.
- [ ] _New_:  The Open GL subsystem exhibits drawing errors where _triangles_ are missing or slowly drawing.  11 FPS. 

![image](https://user-images.githubusercontent.com/118112/178635849-ef3c1dab-d888-40c1-a5ce-75262f8ebb2c.png)

---

This screenshot shows the test app running in the `arm64` architecture mode from the macOS Activity Monitor. Note  _Apple_  in the `kind` column.

![image](https://user-images.githubusercontent.com/118112/178636006-27d447e6-0baf-47e1-8ea1-6401b20371ae.png)

You can determine [which architecture (Intel or Apple) a process is being run](https://apple.stackexchange.com/questions/416036/tell-if-running-process-is-running-under-rosetta-or-is-m1-native-by-command-line) by checking whether a process is run with [Rosetta](https://developer.apple.com/documentation/apple-silicon/about-the-rosetta-translation-environment/).  I do not recommend using Rosetta to run Xcode.

```bash
ps -p `fuser /usr/libexec/rosetta/runtime 2> /dev/null`
```

---

Build version info:

```bash
sw_vers
# ProductName:		macOS
# ProductVersion:	13.0
# BuildVersion:		22A5295i

uname -a
# Darwin m1.local 22.0.0 Darwin Kernel Version 22.0.0: Tue Jun 28 20:48:02 PDT 2022; 
# root:xnu-8792.0.134.131.2~1/RELEASE_ARM64_T8103 arm64

xcodebuild -version
# Xcode 14.0
# Build version 14A5270f
```

**Comment by wipfli** [comment]
Thanks for offering help with testing of simulator crashes on M1 in the Slack channel, @Svantulden. Will ping you when possible...

**Comment by roblabs** [comment]
Closing out this research into Ventura Beta + Xcode 14 Beta, as Xcode Version 14.0 RC (14A309) was released on Sep 7, 2022.

Tracking any GL drawing issues at https://github.com/maplibre/maplibre-gl-native/issues/268

**Comment by chganesh** [comment]
unable to run React native ios app through xcode and real device
<img width="1100" alt="Screenshot 2023-03-27 at 5 55 04 PM" src="https://user-images.githubusercontent.com/14010143/227942559-4d99a178-1526-4d84-af82-3a040604f205.png">

xcode version 14.2
Simulator version 14(16.2)
react-native: 0.70.6
Mac Book pro M1 chipset ventura OS

**Comment by chganesh** [comment]
unable to run React native ios app through xcode and real device
<img width="1100" alt="Screenshot 2023-03-27 at 5 55 04 PM" src="https://user-images.githubusercontent.com/14010143/227942559-4d99a178-1526-4d84-af82-3a040604f205.png">

xcode version 14.2
Simulator version 14(16.2)
react-native: 0.70.6
Mac Book pro M1 chipset ventura OS

**Comment by louwers** [comment]
@chganesh Please see https://github.com/maplibre/maplibre-react-native
