### ISSUE TITLE
iOS, sprite in assets

### ISSUE THREAD

**Issue by VincentBaillet** [maplibre/maplibre-gl-native#367]
Hi all, 
I'm working on a iOS app using Maplibre-gl-native  (version 5.12.2). it works like a charm. But i've a problem displaying icons.

with following line (in the style json file) all the icons are displayed perfectly
  "sprite": "https://maputnik.github.io/osm-liberty/sprites/osm-liberty",

but if i change this line in order to use offline sprites, nothing is displayed, and no errors are raised.
"sprite": "asset://sprites/bright-v8",

I've checked twice that the files bright-v8.json and bright-v8.png are embedded and accessible in the bundle with the required path.

So I suspect that there is a problem accessing the sprites from the bundle.

I'm running out of solutions for this problem. is there a workaround to use local files rather than distant ones ?

best regards

**Comment by VincentBaillet** [comment]
finally achieved to make it work:
- I downloaded osm-liberty sprites from https://maputnik.github.io/osm-liberty/sprites/osm-liberty
- I embedded the files directly at the top of the bundle
everything works well now 

it looks like the problem was simply with the bright-v8 files. can't figure out what's wrong with them (structure looks good, and the requested sprites looks OK too. )

**Comment by wipfli** [comment]
Thanks for posting this solution. Let me close this issue since you seem to have found a fix...
