### ISSUE TITLE
Separate build flavor to avoid any references to non-FLOSS software

### ISSUE THREAD

**Issue by cyBerta** [maplibre/maplibre-gl-native#379]
Delta Chat faces problems to distribute the Android app containing MapLibre in F-Droid. F-Droid considers MapLibre as violating their FOSS principles because it contains references to google gms. Even though we didn’t opt-in the use of the GoogleLocationEngine and thus using any google dependencies in the client, these dependencies are required during compile time. Other software projects do or will face the same problem with F-Droid and MapLibre, e.g. see https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11527)

A contributor proposed to [remove the problematic classes on compile-time](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11532/diffs). While this works, it’s quite a hack. I would like to propose instead to have a separate build flavor that fulfits F-Droids requirements, which has no references to com.google.android.gms.

Problematic classes we identified are:

com/mapbox/mapboxsdk/location/engine/LocationEngineResult.java
com/mapbox/mapboxsdk/location/engine/GoogleLocationEngineImpl.java
com/mapbox/mapboxsdk/location/engine/LocationEngineProvider.java

And some tests.

**Comment by jakoblm** [comment]
Indeed. What is the current progress on this? I ask because it's been over a month since the last comment and there doesn't seem to be any current effort. Correct me if I am wrong. A number of apps are affected. See also: https://gitlab.com/fdroid/fdroidserver/-/issues/1004

**Comment by licaon-kter** [comment]
@jakoblm see latest F-Droid metadata for Element or Delta Chat. And https://gitlab.com/freed-by-fdroid Maplibre was setup for a purpose, but not yet functional. Free free to port those changes to a flavor I guess.

**Comment by jakoblm** [comment]
Thank you for your answer. Unfortunately, this is beyond my capabilities. I am not familiar with the technical details to do that. Is there any collaboration with the F-Droid team to speed this up?

**Comment by licaon-kter** [comment]
Ideally this should be handled here, but... yeah...

**Comment by jakoblm** [comment]
Well, ideally... I became aware of this when I noticed the downgrade of Transportr in F-Droid. 
If I can help to speed up the process, let me know.

**Comment by birkskyum** [comment]
Hi @licaon-kter  @jakoblm , thank you for pushing this. MapLibre should be possible to use in "Libre" software, so let's sort it out in this repo. I raised this topic in the latest Technical Steering Committee meeting because it's essential to resolve, but unfortunately, we haven't been able to address it yet. I'll look into it now to see what can be done. If you have specific ideas for how to resolve it, or even a PR, let me know.

**Comment by licaon-kter** [comment]
@birkskyum as said above, one can look at either https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.b44t.messenger.yml#L1297-L1306 or at https://gitlab.com/freed-by-fdroid/maplibre-gl-native/-/merge_requests/1/diffs to see what needs to be done. This is more a hammer than a scalpel, but for the devs here might provide the start point.

**Comment by jakoblm** [comment]
@birkskyum Thank you for taking care of this now. I had already opened a new issue to move this forward: https://github.com/maplibre/maplibre-gl-native/issues/482

Since I don't understand anything about the technical details, I can't help with this. If there is something else to do, I will try that. 
I think the F-Droid team's ideas are a good approach.

**Comment by licaon-kter** [comment]
How does a new duplicate issue help exactly?

**Comment by jakoblm** [comment]
I didn't know how much more attention this closed issue would get. Obviously that was unnecessary, sorry. If it continues here now, the new duplicate issue can be closed.

**Comment by birkskyum** [comment]
I don't think a build type or product flavour will resolve this, because gradle might still pull in the proprietary code, as mentioned here, so these parts should be conditionally excluded instead https://www.oliverspryn.com/blog/conditional-gradle-configuration-by-build-variant

**Comment by birkskyum** [comment]
Affected Apps:
- [Delta Chat](https://github.com/deltachat/deltachat-android) - [issue](https://github.com/deltachat/deltachat-android/issues/2361), [fix-by-updating](https://github.com/deltachat/deltachat-android/pull/2351), [f-droid](https://f-droid.org/en/packages/com.b44t.messenger/)
- [Transportr](https://github.com/grote/Transportr) - [issue](https://github.com/grote/Transportr/issues/668), [f-droid](https://f-droid.org/en/packages/de.grobox.liberario/)
- [Element](https://github.com/vector-im/) - [issue](https://github.com/vector-im/element-android/issues/6100), [fix-by-excluding](https://github.com/vector-im/element-android/pull/6136), [f-droid](https://f-droid.org/en/packages/im.vector.app/)

What is the current status of these apps? It seems like they still are to be found on f-droid, so weren't they removed anyway?

**Comment by licaon-kter** [comment]
As linked above directly from F-Droid Gitlab, Element (and SchildiChat) and Delta Chat, before building the actual app, we sed clean up maplibre-gl and build a truly libre version of it without proprietary dependencies.

**Comment by wipfli** [comment]
I am new to the F-Droid stuff. What does libre mean in terms of licenses? Is it like only MIT, BSD, and Apache?

**Comment by licaon-kter** [comment]
@wipfli OSI and/or FSF approved https://spdx.org/licenses

Do note that the issue here is the confused use of "libre" in "maplibre". It means the code is "libre licensed" not "buildable from libre code and dependencies".

The current situation is that library artifacts used by apps aro NOT FOSS.

**Comment by wipfli** [comment]
So the problem is that MapLibre GL Native uses libraries which are not OSI? If yes, how did you find this out? I am asking because I would like to better track the licenses of our dependencies, see #296.

**Comment by licaon-kter** [comment]
F-Droid has (better said will have soon) a binary scanner for the resulting APKs, so this, and many more, were found: https://gitlab.com/fdroid/fdroidserver/-/issues/1004

**Comment by ntadej** [comment]
Just for my curiosity, is there an alternative for location services that is F-Droid compliant or are those apps then just without location services?

**Comment by birkskyum** [comment]
I read somewhere that the google location provides added precision, indicating a fallback is in place, but I'm sure about where. I wondered if we could pull the google location out into a plugin so that it isn't in the base SDK.

**Comment by licaon-kter** [comment]
@ntadej `org.osmdroid`directly or via https://github.com/johan12345/AnyMaps

**Comment by ialokim** [comment]
> Just for my curiosity, is there an alternative for location services that is F-Droid compliant or are those apps then just without location services?

AFAIK there's no real alternative for Google location services, but using the [built-in Android location information](https://developer.android.com/reference/android/location/LocationManager) is often good enough. I think they (can?) also take mobile cell location into account.

**Comment by jakoblm** [comment]
Is there any progress on this, or has it been postponed again?

**Comment by wipfli** [comment]
I think nobody has been working on the fdroid issue. Feel free to puah this forward, @jakoblm

**Comment by licaon-kter** [comment]
F-Droid builds maplibre-truly-free for DeltaChat and Element 'nd SchildiChat. 

It would be better to have this clean up done here so F-Droid does not need to rebuild the lib each time one of those app releases an update.

**Comment by ntadej** [comment]
Thanks both for feedback! What Oliver wanted to say is we currently lack Android expertise a bit and any help would be welcome. Otherwise it may take a while for this to happen.

**Comment by jakoblm** [comment]
As already mentioned, I also lack technical expertise in these matters. Therefore, I would not know what I can do. If there is something for me to do, let me know. But I would be very grateful if a solution can be found soon. Maybe some expterts from F-Droid or from affected apps (like Transportr) would be willing to collaborate?

**Comment by licaon-kter** [comment]
You can see what a patch entails here: https://gitlab.com/freed-by-fdroid/maplibre-gl-native/-/merge_requests/1/diffs

That needs to be translated to a gradle flavor.

**Comment by jakoblm** [comment]
@licaon-kter: That sounds great. And what is the current status? Is it realistic that the patch will be out soon, or does it still take time? Thanks for working on this.

**Comment by licaon-kter** [comment]
I guess devs here will comment when they'l

**Comment by birkskyum** [comment]
We finally got the Gradle version of maplibre updated from something quite old to the latest, so that's a step in the right direction.

**Comment by jakoblm** [comment]
@birkskyum: Any progress here?

**Comment by birkskyum** [comment]
@louwers

**Comment by louwers** [comment]
@jakoblm Thanks for the reminder. Not at this point, but we definitely have the Gradle & Android experience with @ovivoda on board right now.

Is the merge reques @licaon-kte shared all it takes? Should be doable to get this sorted this week then.

**Comment by louwers** [comment]
What would be the harm in completely removing this dependency and related code?

Those willing to use Google's propietary location services can provide their own LocationEngine. And someone could publish it as a separate library.

**Comment by birkskyum** [comment]
If it's made in such way that it's trivial to still get the existing solution setup, then it could be a way forward

**Comment by louwers** [comment]
We would need to get rid of the `LocationEngineProvider` class entirely (which chooses a `LocationEngine` based on if Google Play Services are available) and instead require that a `LocationEngine` is passed to `LocationComponent` directly.

We can default to the same `LocationEngine` that is used right now when Google Play Services is not available.

**Comment by boldtrn** [comment]
In my experience, Google's Fused Location Provider provides better results, compared to native Android.

The current code works pretty well because it can provide both providers, depending on what the device is capable of.

I understand that F-Droid has the requirement. 

On the other hand I feel like the default behaviour should provide the best location provider (GMS). So some excluding logic for special builds would be my vote if it's possible, if not, we should make it super easy for everyone to use the current logic.

**Comment by louwers** [comment]
@boldtrn Thanks for pitching in. I am working on a refactor.  You can pass your own `LocationEngine` to the `LocationComponent` via `LocationComponentActivationOptions`. To get the same behavior you would have to copy the `GoogleLocationEngineImpl` to your own source tree. You would also have to include the logic to choose a  `LocationEngine` i.e. the essentially the `if` statement in `LocationEngineProvider`.

https://github.com/maplibre/maplibre-gl-native/blob/ea234edf67bb3aec75f077e15c1c30c99756b926/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/engine/LocationEngineProvider.java#L49

**Comment by boldtrn** [comment]
@louwers, thanks for the info, we have a custom implementation of this already for the Kurviger app. I just meant that IMHO we should avoid exactly this, like adding a note in the README along the lines of:

> If you would like the best location results, please copy this class to your codebase. Then there are 100s of apps out there that have to copy this.

**Comment by birkskyum** [comment]
I understand the minor inconvenience this might bring to our users, but I still think we should move the proprietary software out of the SDK, and provide as straightforward migration instructions as possible.

**Comment by louwers** [comment]
@birkskyum I agree. I updated the pull request to make `LocationEngineImpl` and `LocationEngineProxy` public so that the Google Play services location provider can be implemented outside MapLibre GL Native for Android. Right now it would be a copy paste job, but hopefully someone will make this code available as a package.

**Comment by jakoblm** [comment]
Great. 
@licaon-kter What are the necessary steps to get the latest releases of apps like Transportr back into F-Droid? Do the respective developers have to integrate the current Maplibre version or does the F-Droid team do it?

**Comment by louwers** [comment]
@jakoblm Please discuss this in the appropiate place. This is the MapLibre repo. Thanks.

**Comment by licaon-kter** [comment]
We can be on topic, maplibre needs to tag a release and publish the new version to maven first.

**Comment by louwers** [comment]
@licaon-kter https://github.com/maplibre/maplibre-gl-native/releases/tag/android-v10.0.0 😉
