### ISSUE TITLE
Rename primary branch to `main`

### ISSUE THREAD

**Issue by nyurik** [maplibre/maplibre-gl-native#38]
We need to rename this repo's primary branch to `main` as described in https://github.com/github/renaming .  I could do it myself but only after other contributors are made aware of it. Thx!

**Comment by petr-pokorny-1** [comment]
There is a bit more to do - master branch is referenced in workflows and scripts. We need to rename it there and test everything:

## Workflows: 

https://github.com/maplibre/maplibre-gl-native/blob/1329c8c2fcbef5c12ac849347740829e2e311bfa/.github/workflows/android-ci-pull.yml#L7
https://github.com/maplibre/maplibre-gl-native/blob/1329c8c2fcbef5c12ac849347740829e2e311bfa/.github/workflows/android-ci.yml#L14
https://github.com/maplibre/maplibre-gl-native/blob/1329c8c2fcbef5c12ac849347740829e2e311bfa/.github/workflows/ios-ci.yml#L17
https://github.com/maplibre/maplibre-gl-native/blob/1329c8c2fcbef5c12ac849347740829e2e311bfa/.github/workflows/macos-ci.yml#L14

## ios pinning script

https://github.com/maplibre/maplibre-gl-native/blob/1329c8c2fcbef5c12ac849347740829e2e311bfa/platform/ios/scripts/nitpick/submodule-pin.js#L9

## macos document generation script:

https://github.com/maplibre/maplibre-gl-native/blob/1329c8c2fcbef5c12ac849347740829e2e311bfa/platform/ios/platform/macos/scripts/document.sh#L27

## Other

There are additional scripts which I am not sure if they are being used:

https://github.com/maplibre/maplibre-gl-native/blob/1329c8c2fcbef5c12ac849347740829e2e311bfa/platform/ios/scripts/environment.js#L27

**Comment by ntadej** [comment]
This has been done.
