### ISSUE TITLE
Automated UI Tests for iOS

### ISSUE THREAD

**Issue by roblabs** [maplibre/maplibre-gl-native#39]
Initial Automated UI Tests demo for Xcode

- [x] Create initial UITest _scaffolding_ for iOS
- [x] Add UITests based on `XCTest` with deployment target of iOS `9.0`
- [x] Save a PNG screenshot to the UITest results. Add `XCTest` extension for screenshots
- [x] Provide PNG & Video .MOV samples to demonstrate automated UITests running in Xcode
- [x] Add flag to `make iproj CI=1` to run in headless mode (for GitHub Actions & Xcode Server Bots)
- [x] Add UITests for the Scheme `iosapp`
- [x] Enable UITests for the Scheme `bench` while in the `iosapp` scheme
- [x] For the Scheme `bench`, Write the Benchmark log to the Documents Directory of the Simulator or Device to facilitate testing of many Benchmarking runs and iterations for testing FPS.  Useful for Metal versus Open GL testing.
- [x] Review tests for for FPS performance (for example, for Metal)
- [x] Add Zero Configuration (Zeroconf) Styles to the Scheme `iosapp` to facilitate automated testing without an access token nor secrets (for GitHub Actions & Xcode Server Bots).
  - [ ] Add tests for other tile providers and TileJSON sources
- [x] Demonstrate automated UITests running in GitHub Actions
- [x] Demonstrate with Xcode Server Bots (XCS) for locally made builds.
- [ ] Determine where Xcode `xcresult` result bundles should be stored (for example, attached as part of a release)
- [x] Test with command line builds (`xcodebuild` & `make test`)
- [x] Demonstrate running automated UI Tests in AWS Device Farm
- [x] Submit PR from working branch https://github.com/roblabs/maplibre-gl-native/commits/uitests

---

Sample Test PNG & MOV
 
* setup initial conditions for position (0,0) and debug settings
* Take a screenshot
* Current source (easier to view in Xcode) - https://github.com/roblabs/maplibre-gl-native/blob/uitests/platform/ios/platform/ios/iosapp%20UITests/iosapp_UITests.swift#L38,L44

Sample output file saved in `.xcresult`
*MapLibre-Screenshot-Null Island Tiles-iPhone 6s-13.7.png*
<img src="https://user-images.githubusercontent.com/118112/110050102-0ad6ed00-7d08-11eb-857a-80a53ea39d93.png" width=25%>

---

---

**Comment by roblabs** [comment]
- [x] Add Zero Configuration (Zeroconf) Styles to the Scheme `iosapp` to facilitate automated testing without an access token nor secrets (for GitHub Actions & Xcode Server Bots).

Screen recording of Zeroconf Tiles using Xcode 12.5

https://user-images.githubusercontent.com/118112/110371008-3f48f280-8001-11eb-92f1-acfe3ca7af37.mov

**Comment by wipfli** [comment]
Can this be closed @roblabs? It looks like to implemented automated ui tests in #47...
