### ISSUE TITLE
C++20, improved compile times

### ISSUE THREAD

**Issue by birkskyum** [maplibre/maplibre-gl-native#390]
I think we could progress much faster if we had a faster CI/CD check, because these 2h per small change is quite a long time.

I have been looking at our options, and the lowest hanging fruit in this case like is upgrading to C++20, and leaning into the import/export of modules rather than #include.

That should reduce the compile times quite a lot because the modules are compiled only once rather than every time they are included. 

Especially the ios-ci workflow alone takes >100 minutes to go through, and it's mainly spending time compiling.

**Comment by ntadej** [comment]
I think we should just make sure `ccache` is enabled for all tests (currently it's certainly not).

C++ modules will not really help with cold builds. In C++ headers do not mean that everything is recompiled each time as they just reference the actual code.

**Comment by birkskyum** [comment]
Ah, okay. Was just reading through some pages like these https://www.incredibuild.com/blog/what-you-need-to-do-to-move-on-to-c-20-the-complete-list

**Comment by ntadej** [comment]
This is also not that supported yet. The first step would be to move to C++17 where we can also drop a lot of polyfills Mapbox implemented.

**Comment by birkskyum** [comment]
I believe the code already compiles with C++, so that sounds like a good idea to actually see how much we can gain from that

**Comment by ntadej** [comment]
No, there are some warnings with C++17 still with some platforms. Qt6 does use C++17 though, but I had to use some ifdefs to make it compile without warnings.

**Comment by birkskyum** [comment]
Oh yes I see. That should of course be resolved first. So all this ghc::filesystem could for instance be remove right?

**Comment by ntadej** [comment]
And optionals and many other classes, but I can't remember all from the top of my head.

**Comment by birkskyum** [comment]
It's really a great area to investigate, so if you see anything that potentially can be pulled out I'd be happy to give it a shot.

**Comment by ntadej** [comment]
I think we need to finalise the CI setup first as discussed yesterday. Or we need people reviewing much more thoroughly. My previous cleanups did cause some regressions by accident unfortunately 😊
