### ISSUE TITLE
Qt: Undefined references while linking on Windows/MinGW

### ISSUE THREAD

**Issue by kiibimees** [maplibre/maplibre-gl-native#394]
Curret configuration adds import/export declaration into headers when MBGL_QT_INSIDE_PLUGIN is used. MSVC linker doesn't complain but building on MinGW gives a bunch on errors like:
`
qgeomappingmanagerenginemaplibregl.cpp:(.text+0x700): undefined reference to __imp__ZN11QMapLibreGL8SettingsC1Ev
qgeomappingmanagerenginemaplibregl.cpp:(.text+0xb29): undefined reference to __imp__ZNK11QMapLibreGL8Settings13defaultStylesEv
`

**Comment by ntadej** [comment]
Will have a look soon. Need to setup the MinGW CI pipeline.

**Comment by kiibimees** [comment]
No worry, I have a fix for it. I will submit soon...

**Comment by ntadej** [comment]
Interestingly Qt5 with older MinGW works just fine: https://github.com/maplibre/qt-geoservices-maplibre-gl/actions/workflows/Windows-Qt5.yml

**Comment by kiibimees** [comment]
> Interestingly Qt5 with older MinGW works just fine

Yeah, strange. Perhaps it's caused by newer MinGW/GCC versions.

**Comment by kiibimees** [comment]
@ntadej , do you have some time to review and merge this change in the near future? It's a small change and It would be nice to include it already when I rebase MapLibre plugin in Qt 6.

**Comment by ntadej** [comment]
Yes, will be merged once the rebased pipeline finishes.

**Comment by ntadej** [comment]
This is now merged.

If you plan to rebase the plugin in Qt repository, I would propose you use also the changes from https://github.com/maplibre/qt-geoservices-maplibre-gl. I can sync back any other changes you may make.

**Comment by kiibimees** [comment]
Thank you very much! I had a brief look at the separate plugin repo but didn't spot any significant changes other than Qt 5 support. Naming (namespace) changes I already applied myself when upgrading MapLibre version. Now we need to fix some serious bugs like wrong clipping and crash in certain conditions. I will either file a bug or try to find a solution.

**Comment by ntadej** [comment]
Note that wrong clipping does not occur in Qt 5 with the same MapLibre version so it may be an upstream Qt rendering bug.

**Comment by kiibimees** [comment]
> Note that wrong clipping does not occur in Qt 5
Yes, I remember you said that. Most probably it's caused by the redesign of the whole graphics stack in Qt 6 but I just haven't had time to investigate it.

Anyways, my rebased changes are here:
https://codereview.qt-project.org/c/qt/qtlocation/+/401091/2

**Comment by ntadej** [comment]
I will close this one for now and open a new ticket for the plugin in its dedicated repo.
