### ISSUE TITLE
Performance issues on iOS 14

### ISSUE THREAD

**Issue by degtiarev** [maplibre/maplibre-gl-native#46]
Hi. There are performance issues that appears when there's any Custom annotation in the current viewpoint on mapview. I guess these issues are critical for anyone who shows Custom annotations on mapview.

They are noticeable even in [this](https://docs.mapbox.com/ios/maps/examples/annotation-views/) simple example from mapbox doc.

Mapbox team fixed them in [v6.2.0](https://github.com/mapbox/mapbox-gl-native-ios/releases/tag/ios-v6.2.0). These are two issues from [mapbox/mapbox-gl-native-ios](https://github.com/mapbox/mapbox-gl-native-ios) connected with them:
1. On iOS 14 MGLAnnotationView slows down map significantly [#350](https://github.com/mapbox/mapbox-gl-native-ios/issues/350)
2. Fix map stuttering by switching render call to use setNeedsDisplay [#411](https://github.com/mapbox/mapbox-gl-native-ios/pull/411)

[This](https://github.com/maplibre/maplibre-gl-native/commit/58487a9638166cdf6bc2295f6b08e20e3cb0bcf9) commit does not fix the issues I described.

**Comment by petr-pokorny-1** [comment]
I did have a look into the issue and there doesn’t seem to be any related changes in the core library so hopefully  the fix could be cherry picked from https://github.com/mapbox/mapbox-gl-native-ios/pull/411/files?file-filters%5B%5D=.h&file-filters%5B%5D=.md&file-filters%5B%5D=.mm

**Comment by juhieta** [comment]
Hi @petr-pokorny-1 @degtiarev,

Yes it seems that relevant parts of https://github.com/mapbox/mapbox-gl-native-ios/pull/411/files can be applied and in my tests seems to fix the performance issue with annotations. Created PR https://github.com/maplibre/maplibre-gl-native/pull/60

**Comment by roman-mykitchak** [comment]
Hi, Is it already cherry picked and resolved by Maplibre team?
I also have slow down(stuttering) on zoom while using MGLAnnotationView instead of MGLAnnotationImage.
Any progress with this pig from Mapbox?

**Comment by juhieta** [comment]
Hi @roman-mykitchak, yes the [cherry pick PR](https://github.com/maplibre/maplibre-gl-native/pull/60) was merged to master, have you tried the performance with the latest version? However the PR seems to cause some assertion failure in metal-support -branch as noted [here](https://github.com/maplibre/maplibre-gl-native/pull/60#issuecomment-824129436). So we'll need to have look what is causing that before closing this issue.

**Comment by juhieta** [comment]
Hi @ferologics, unfortunately it has not yet been released (the last iOS release was done before the #60 merge). There's this one [assertion check fail](https://github.com/maplibre/maplibre-gl-native/pull/60#issuecomment-824129436) that needs to be checked on the Metal branch. Btw, if [MGLSymbolStyleLayer and MGLShapeSource](https://docs.maptiler.com/maplibre-gl-native-ios/Classes-MGLSymbolStyleLayer/) work for your use case, they are better performing option in general.

**Comment by ferologics** [comment]
@juhieta thanks for the pointer, unfortunately we have to use custom annotation views. I suppose there won't be a release before Metal support is rolled out @petr-pokorny-1 ? 

Could anyone instruct me on how to test with this change in a fork? As simple as pointing to master branch? Or do we need to build and point to a custom binary with the change?

**Comment by wipfli** [comment]
I think there was a release since the last comment. Did you see performance improvements, @ferologics or @degtiarev?
