### ISSUE TITLE
Remove or Upgrade android-sdk-versions-plugin to latest version

### ISSUE THREAD

**Issue by birkskyum** [maplibre/maplibre-gl-native#484]
The android-sdk-versions-plugin is currently blocking an Upgrade of Grade #483 .

The mapbox/android-sdk-versions-plugin [repo](https://github.com/mapbox/android-sdk-versions-plugin) isn't publishing the latest changes to [maven central](https://search.maven.org/artifact/com.mapbox.mapboxsdk/mapbox-android-sdk-versions/1.1.0/jar), with the latest published version being 1.1.0, and the latest repo version 1.1.3.

The version we need is >= 1.1.1.

We can publish it in our Nexus account and move to it instead. 

Work on cloning and publishing it can be found in here: https://github.com/birkskyum/android-sdk-versions-plugin

**Comment by birkskyum** [comment]
@carlonzo is this something you have experience with and can help with? publishing to maven central i mean?

**Comment by carlonzo** [comment]
Sure I could have a look. I guess the authentication is already setup on CI?

Otherwise I had a look last time at removing the plugin, given that I can't find any reference in code to the file generated by the plugin (it's a file containing the version of the MapLibre SDK). Would you consider the option to remove it otherwise, if we prove that the SDK works without it?

**Comment by birkskyum** [comment]
If it isn't in use I think removing it makes a lot of sense

**Comment by birkskyum** [comment]
It says on the plugin readme site that 

>All Mapbox android SDK modules that incorporate the Telemetry SDK and meant to be released as libraries(artifacts) should apply this plugin to facilitate the Telemetry SDK access all Mapbox library versions at run time.

And given that we don't have telemetry at all, maybe that's why it isn't in use

**Comment by birkskyum** [comment]
I'll be damned, removing it and upgrading gradle seems to work (:
