### ISSUE TITLE
Setup M1 build runners

### ISSUE THREAD

**Issue by birkskyum** [maplibre/maplibre-gl-native#485]
This is a tracking issue for the current setup of 3 x m1 build runners on AWS, which has the following configuration:

Hardware:
- M1 mac mini
- 256GB EBS storage

Software:
- xcode v14
- tmux
- homebrew
- nvm (with node 18)
- ninja
- xcpretty
- python3 (through homebrew)

Status on machines

- [X] Machine 1 (34-218-210-7)
- [X] Machine 2 (18-236-103-245)
- [X] Machine 3 (3.80.132.4)

**Comment by ntadej** [comment]
Python seems to be needed for Qt install action.

**Comment by birkskyum** [comment]
@ntadej , there are 2 runners running now, both with python

**Comment by birkskyum** [comment]
Awaiting a resolution of this #494 to unblock the CI.
