### ISSUE TITLE
[test] Results of testing MapLibre `android-v9.4.0` & `ios-v5.11.0`

### ISSUE THREAD

**Issue by roblabs** [maplibre/maplibre-gl-native#49]
# Summary 

* Testing results of MapLibre `android-v9.4.0` & `ios-v5.11.0` released on Mar 12, 2021
* Android tested on the Emulator with the AWS Location sample from https://github.com/aws-samples/amazon-location-samples/pull/11
* iOS tested on Devices & Simulator with the AWS Location sample from https://github.com/aws-samples/amazon-location-samples/pull/10
* iOS tested on Devices & Simulator with the Geography Class sample from https://github.com/roblabs/openmaptiles-ios-demo/commit/7b1a711b80167c76a73bb7dbbb441ac0738ea31a

---

# Detailed Notes 

## Android Tests for Release

Using release — https://github.com/maplibre/maplibre-gl-native/releases/tag/android-v9.4.0

### AWS Location Tests for MapLibre `android-v9.4.0`

- [x] Upgrade MapLibre for iOS from `android-v9.2.1` to `android-v9.4.0` in the project https://github.com/roblabs/amazon-location-samples/tree/main/mapbox-gl-native-android
- [ ] Wireshark network traffic for telemetry on various tile sets

<img src="https://user-images.githubusercontent.com/118112/111005417-9f140600-833f-11eb-83b1-bb1af48c5535.png" width=100%>

#### Geography Class Tests for MapLibre `android-v9.4.0`

- [x] Upgrade MapLibre for iOS from `android-v9.2.1` to `android-v9.4.0` in the project https://github.com/roblabs/osm2vectortiles-android

<img src="https://user-images.githubusercontent.com/118112/111014573-2e79e300-8359-11eb-906d-f84f9aa6e571.png" width=50%>
---

## iOS Tests for Release

Using release — https://github.com/maplibre/maplibre-gl-native/releases/tag/ios-v5.11.0

- [x] Using Xcode Server Bots, build the test app `iosapp` for Simulators & local Wireless devices
- [ ] Wireshark network traffic for telemetry on various tile sets

#### Geography Class Tests for MapLibre `ios-v5.11.0`

- [x] Upgrade MapLibre for iOS from `5.10.0` to `5.11.0` in the project https://github.com/roblabs/openmaptiles-ios-demo
- [x] Deploy `Geography Class.app` to a device
- [x] While adding MapLibre in Swift Packages to your project, use *Up to Next Major*:  `5.11.0`.  Or something appropriate for your project
  * [maplibre-gl-native-distribution/issues/3](https://github.com/maplibre/maplibre-gl-native-distribution/issues/3) is still an open issue (but very minor)
  - [x] Verify in the Swift Packages Manager that MapboxEvents has been removed
- [x] Long press on the Info Button and note down its response, "Mapbox Maps SDK for iOS 5.11.0"
- [x] Verify Readme.md as it is shown in Xcode

---

While adding MapLibre in Swift Packages to your project, use *Up to Next Major*:  `5.11.0`.

<img src="https://user-images.githubusercontent.com/118112/110995677-9a475600-832f-11eb-849e-f7175f86e29f.png" width="30%">

---

Verify in the Swift Packages Manager that MapboxEvents has been removed
<img src="https://user-images.githubusercontent.com/118112/110995810-cd89e500-832f-11eb-970c-2e829d19c245.png" width="30%">

---

Geography Class running MapLibre `5.11.0` on an iPhone SE
<img src="https://user-images.githubusercontent.com/118112/110996971-9288b100-8331-11eb-8945-f1203e493cfd.png" width="30%">

---

### AWS Location Tests for MapLibre `5.11.0`

- [x] Upgrade MapLibre for iOS from `5.10.0` to `5.11.0` in the project https://github.com/roblabs/amazon-location-samples/tree/main/mapbox-gl-native-ios
- [x] Upgrade CocoaPods, as there may be references to MapboxEvents.  It's a good idea to clear the pod cache, see `pod -h` for guidance.  There may be build issues if you do not clear the pod cache.
- [x] While adding MapLibre in Swift Packages to your project, use *Up to Next Major*:  `5.11.0`.
- [x] Verify in the Swift Packages Manager that MapboxEvents has been removed
- [x] Enable the Info button, since this project disables it:  `mapView.attributionButton.isHidden = true`
- [x] Long press on the Info Button and note down its response, "Mapbox Maps SDK for iOS 5.11.0"
- [x] Deploy `Amazon Location Service Demo.app` to a device

---

*After:* MapLibre `5.11.0` Swift Package in AWS

<img src="https://user-images.githubusercontent.com/118112/110995312-ff4e7c00-832e-11eb-842f-4a8495bf145b.png" width="30%">

---

*Before:* MapLibre `5.10.0` Swift Package in AWS
<img src="https://user-images.githubusercontent.com/118112/110995364-1beab400-832f-11eb-997d-6e56a71354b3.png" width="30%">

---

While adding MapLibre in Swift Packages to your project, use *Up to Next Major*:  `5.11.0`.

<img src="https://user-images.githubusercontent.com/118112/110995677-9a475600-832f-11eb-849e-f7175f86e29f.png" width="30%">

---

Verify in the Swift Packages Manager that MapboxEvents has been removed
<img src="https://user-images.githubusercontent.com/118112/110995810-cd89e500-832f-11eb-970c-2e829d19c245.png" width="30%">

---

AWS Location running MapLibre `5.11.0` on an iPhone SE
<img src="https://user-images.githubusercontent.com/118112/110995125-aed71e80-832e-11eb-85f0-f782b41be17d.png" width="30%">

**Comment by petr-pokorny-1** [comment]
@roblabs can we close this one?
