### ISSUE TITLE
Include macOS binaries in XCFramework

### ISSUE THREAD

**Issue by chrisballinger** [maplibre/maplibre-gl-native#5]
The existing XCFramework you're distributing could be expanded to include the macOS platform alongside iOS and iOS Simulator (and Mac Catalyst)

**Comment by petr-pokorny-1** [comment]
The SDK for MacOS has different APIs than SDK for iOS. I am not sure but I think slices in XCFramework should have the same APIs for all supported platforms.

**Comment by chrisballinger** [comment]
If it's significantly different for AppKit than maybe it's worth distributing separately, however, Mac Catalyst would have the same API as the iOS builds

**Comment by roblabs** [comment]
While building for Mac Catalyst using MapLibre [`v5.10.0`](https://github.com/maplibre/maplibre-gl-native-distribution/releases/tag/5.10.0):

Current error is

> While building for Mac Catalyst, **no library for this platform was found** in '/Users/roblabs/Library/Developer/Xcode/DerivedData/openmaptiles-ios-demo-btjolluihnwewhdsquzewzkiemgj/SourcePackages/artifacts/maplibre-gl-native/Mapbox.xcframework'.


The path `.../SourcePackages/artifacts/maplibre-gl-native/` is where the Swift Packages artifacts are downloaded to.

---

Test App settings:

![image](https://user-images.githubusercontent.com/118112/108633074-24825580-7427-11eb-97f8-2635c6b1148c.png)

**Comment by petr-pokorny-1** [comment]
Mac Cataylist is tracked under https://github.com/maplibre/maplibre-gl-native/issues/3
Closing.
