### ISSUE TITLE
[Android] - Disable mapbox access token

### ISSUE THREAD

**Issue by sjoerdhuininga** [maplibre/maplibre-gl-native#51]
At the moment it seems the Android SDK will crash when you provide an invalid access token (defined as it being NULL or not starting with either PK or SK). Since we're not using Mapbox but our own tileset we don't really need a Mapbox token.

**Current behaviour**
App crashes when not entering a Mapbox token

**Expected behaviour**
App doesn't crash when leaving an empty Mapbox token

**Comment by cdiaz** [comment]
I have same problem

**Comment by petr-pokorny-1** [comment]
There is a PR #90 which addresses this problem, after it will be merged and released developer will be able to use `Mapbox.getInstance(Context context)` overload without access token.
