### ISSUE TITLE
glfw platform - incorrect url

### ISSUE THREAD

**Issue by jwinarske** [maplibre/maplibre-gl-native#54]
https://github.com/maplibre/maplibre-gl-native/blob/master/platform/glfw/glfw_view.cpp#L417

**Comment by wipfli** [comment]
Can you share more details on this, @jwinarske?

**Comment by jwinarske** [comment]
@wipfli https://github.com/maplibre/maplibre-gl-native/blob/main/platform/glfw/glfw_view.cpp#L428
It's an invalid url, as the endpoint starts with `docs.mapbox.com`.

**Comment by wipfli** [comment]
Ah thanks @jwinarske I copy the permalink https://github.com/maplibre/maplibre-gl-native/blob/afd2bfe6e2b27c5c8e30e5772ff640858f1e3ae0/platform/glfw/glfw_view.cpp#L428

Would you like to fix this in a pull request?

**Comment by wipfli** [comment]
That is a dead link anyway...

**Comment by wipfli** [comment]
I think we could use https://maplibre.org/maplibre-gl-js-docs/assets/us_states.geojson

**Comment by jwinarske** [comment]
https://github.com/maplibre/maplibre-gl-native/pull/316
