### ISSUE TITLE
Flickering/flashing labels while camera is moving

### ISSUE THREAD

**Issue by bsudekum** [maplibre/maplibre-gl-native#56]
_Using MapLibre @ v5.11.0_

I'm seeing a problem with flickering/flashing labels while the camera is tracking the user's location and moving. I understand https://github.com/maplibre/maplibre-gl-native/pull/34 was merged and looks to solve a similar problem, but it seems it is still persisting.

Video of the problem:

https://user-images.githubusercontent.com/1058624/112551640-90394480-8d7e-11eb-8c22-e25819fc0921.mov

Example code:

```swift
import UIKit
import Mapbox

class ViewController: UIViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let mapView = MGLMapView(frame: view.bounds)
        mapView.styleURL = URL(string: "https://your-style.json")!
        mapView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        mapView.showsUserLocation = true
        mapView.userTrackingMode = .followWithCourse
        view.addSubview(mapView)
    }
}
```
Then set your location to `Freeway Drive` in the simulator.

/cc @petr-pokorny-1

**Comment by geolives** [comment]
Same issue for me by using Camera animations to move the camera. 
Some labels (not all) flickers like in the video.

**Comment by nvanfleet** [comment]
I have also seen this in 5.12.0.

**Comment by nvanfleet** [comment]
@nnhubbard I see you recently fixed something in 5.12.1. I don't think that is this issue here. But I've only seen it in iOS which makes me feel like this problem is iOS only as well.

**Comment by nnhubbard** [comment]
@nvanfleet I have tested, and I do not see the flickering issue in my iOS app.

**Comment by nvanfleet** [comment]
@nnhubbard okay interesting. I am wondering if it's something around how I am updating the camera position. Thanks for looking

**Comment by nnhubbard** [comment]
@nvanfleet What method are you using to update the camera position? Here is what I am using:

```
CAMediaTimingFunction *timingFunction = [CAMediaTimingFunction functionWithName:kCAMediaTimingFunctionEaseOut];
[self.mapboxMapView setCamera:camera withDuration:1.0 animationTimingFunction:timingFunction completionHandler:nil];
```

**Comment by nvanfleet** [comment]
@nnhubbard  that is a good question. I think that in general I'll call `- (void)setCamera:(MGLMapCamera *)camera withDuration:(NSTimeInterval)duration animationTimingFunction:(nullable CAMediaTimingFunction *)function edgePadding:(UIEdgeInsets)edgePadding completionHandler:(nullable void (^)(void))completion;` on every location update. I think the amount of time the animation will go for will be 1 second with a linear timing function.

**Comment by nnhubbard** [comment]
@nvanfleet And doing that, you are still having flickering issues? Are you using the most current version of `mapLibre`? Are you building the `.xcframework` yourself?

**Comment by nvanfleet** [comment]
> @nvanfleet And doing that, you are still having flickering issues? Are you using the most current version of `mapLibre`? Are you building the `.xcframework` yourself?

Yes still seeing the issue. I have seen it from 5.12.0 and 5.12.1. I am building the framework using a bazel build file.

**Comment by nnhubbard** [comment]
I would be interested in testing your `.xcframework` file to see if it shows the issues that I am not seeing.

**Comment by junwu-lyft** [comment]
Hi Nick,

Could you try to repro the issue with map style appended in this ticket?
https://github.com/maplibre/maplibre-gl-native/issues/137
I'm wondering that whether this is style related.

It will be very helpful if you can try [repro the issue on official demo](https://github.com/maplibre/maplibre-gl-native/issues/137) with your map style.

Much appreciated!

**Comment by nnhubbard** [comment]
Yes, I can replicate the issue using those steps and checking out a brand new repo.

I was also able to replicate the issue in my app this time. However, I was only able to replicate the bug when using `userTrackingMode`, this is when it was happening. I do not use the `userTrackingMode` in my app, that is why I do not normally see the issue, I only tested it to get to the bottom of this issue.

Are you using the `userTrackingMode`? I handle all of the moving the map, rotation, current user location indicator in my own code, since I want full control over it. That is why I am not seeing the bug in my app. As mentioned on github, instead of the `userTrackingMode`, I am animating the map movements by create a camera object then animating it:

```
CAMediaTimingFunction *timingFunction = [CAMediaTimingFunction functionWithName:kCAMediaTimingFunctionEaseOut];
[self.mapboxMapView setCamera:camera withDuration:1.0 animationTimingFunction:timingFunction completionHandler:nil];
```

**Comment by junwu-lyft** [comment]
We fixed this issue, see: https://github.com/maplibre/maplibre-gl-native/issues/137
