### ISSUE TITLE
Color Alpha Zero Error (Grab has bugfix)

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-native#567]
## Summary

Zero alpha should not impact RGB Value.

For example: Level 12 color : rgba(1.0, 0.0, 0.0, 0.0). Level 13 Color : rgba(1.0, 0.0, 0.0,
1.0). Then level 12.5 should be rgba(1.0, 0.0, 0.0, 0.5).If we adjust RGB Value, the level 12 real
value will be rbga(0.0, 0.0, 0.0, 0.0) which may same with origin color rgba(1.0, 0.0, 0.0, 0.0) full
trasparent, but it will impact 12.5 to rgba(0.5, 0.0, 0.0, 0.5), So we should remain all RGB values
not modify it by alpha.

## Grab has bugfix

The original author of this bug report is Grab. They have a bug fix and would like to upstream it to MapLibre GL Native.

**Comment by alanchenboy** [comment]
same with https://github.com/maplibre/maplibre-gl-native/issues/568 not a issue if we continue use premultiply color

**Comment by ovivoda** [comment]
closing this one as it was a false report.
