### ISSUE TITLE
[BUG] binding.gyp not found

### ISSUE THREAD

**Issue by psociety** [maplibre/maplibre-gl-native#579]
**Describe the bug**
Install fails and i don't understand why. It seems to fail to find the build and when trying to compile it also fails with the following error:
`npm ERR! gyp: binding.gyp not found (cwd: C:\Users\yo\Desktop\js\node_modules\@maplibre\maplibre-gl-native) while trying to load binding.gyp`

**Platform information (please complete the following information):**

```bash
O.S: Windows 10
check checked for "C:\Users\yo\Desktop\js\node_modules\@maplibre\maplibre-gl-native\lib\node-v93\mbgl.node" (not found)
npm ERR! gyp info using node-gyp@8.3.0
npm ERR! gyp info using node@16.13.1 | win32 | x64
npm ERR! gyp info find Python using Python version 3.11.1
npm ERR! gyp info find VS using VS2019 (16.11.32126.315) found
````
I'm sure this may be my problem but i don't understand what i need to do to fix it so the package can be installed :S

**Comment by louwers** [comment]
Hello @psociety thank you for trying out MapLibre. This is a monorepo with many different platforms. Could you give more details about what you are trying to install?

For support please create a thread on [GitHub Discussions Q&A](https://github.com/maplibre/maplibre-gl-native/discussions/categories/q-a) or join us in `#maplibre-native`on [Slack](https://slack.openstreetmap.us/).

**Comment by louwers** [comment]
Maybe this is helpful. https://stackoverflow.com/questions/42638918/cannot-npm-install-due-to-node-gyp-binding-gyp-not-found

**Comment by psociety** [comment]
I apologize for opening an issue, i didn't know about the forum section to make questions.
Thank you for taking your time on finding me an article to follow on! 
I will close the issue to avoid filling maplibre issues sectino with nonissues.
