### ISSUE TITLE
Make an iOS release

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-native#584]
Make an iOS release. I don't know what this involves exactly but let's keep track of this here...

**Comment by wipfli** [comment]
Last one was a bit more than one year ago: https://github.com/maplibre/maplibre-gl-native/releases/tag/ios-v5.12.2

**Comment by wipfli** [comment]
For iOS, there seem to be two workflows:

* release: https://github.com/maplibre/maplibre-gl-native/blob/main/.github/workflows/ios-release.yml
* pre-release: https://github.com/maplibre/maplibre-gl-native/blob/main/.github/workflows/ios-pre-release.yml

**Comment by wipfli** [comment]
The trigger for this action is also just a workflow dispatch. I am curious what happens when I trigger this action...

**Comment by wipfli** [comment]
The logic for the iOS release seems to be mostly in  platform/ios/scripts/deploy-swift-package.sh

**Comment by wipfli** [comment]
Which can be found here: https://github.com/maplibre/maplibre-gl-native/tree/main/platform/ios/platform/ios/scripts (and not here: https://github.com/maplibre/maplibre-gl-native/tree/main/platform/ios/scripts as the unattentive reader might have thought)

**Comment by louwers** [comment]
> The trigger for this action is also just a workflow dispatch. I am curious what happens when I trigger this action...

@wipfli Did you try? :smile:

**Comment by wipfli** [comment]
I can't remember if I triggered the ios release workflow. Feel free to do it and maybe keep track of the steps here in this issue...

**Comment by wipfli** [comment]
Looks like I did not trigger. You can see the workflow runs here: https://github.com/maplibre/maplibre-gl-native/actions/workflows/ios-release.yml

**Comment by louwers** [comment]
I needed to manually update https://github.com/maplibre/maplibre-gl-native-distribution

This should be automated.
