### ISSUE TITLE
Make an Android release

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-native#585]
Similar to #584, we also want an Android release...

**Comment by wipfli** [comment]
The last one was a bit more than 1 year ago: https://github.com/maplibre/maplibre-gl-native/releases/tag/android-v9.5.2

**Comment by wipfli** [comment]
The android release workflow seems to only have a manual trigger:

https://github.com/maplibre/maplibre-gl-native/blob/a405d7a9b33563ae6d3aabd55f075976b0219b24/.github/workflows/android-release.yml#L3-L4

**Comment by wipfli** [comment]
I am tempted to just run this one and see where it crashes...

**Comment by wipfli** [comment]
Hm I did not find any documentation on how to run the release. So let's just try...

**Comment by wipfli** [comment]
![image](https://user-images.githubusercontent.com/53421382/206790057-e41ed290-8ec1-41d6-b49a-655ee1b4e043.png)

**Comment by wipfli** [comment]
https://github.com/maplibre/maplibre-gl-native/actions/runs/3660524523/jobs/6187766501

**Comment by wipfli** [comment]
It seems to be waiting for a self-hosted ubuntu runner. 

```
Requested labels: self-hosted, ubuntu-20.04
Job defined at: maplibre/maplibre-gl-native/.github/workflows/android-release.yml@refs/heads/main
Waiting for a runner to pick up this job...
```

Do we even still have self-hosted ubuntu runners?

**Comment by wipfli** [comment]
#587 makes the android-release.yml workflow run just on the normal github runners.

**Comment by wipfli** [comment]
Next attempt: https://github.com/maplibre/maplibre-gl-native/actions/runs/3660654651/jobs/6188035491

**Comment by wipfli** [comment]
I think this will crash at the firebase test step.

**Comment by wipfli** [comment]
How were the release notes generated in the past? Like here: https://github.com/maplibre/maplibre-gl-native/releases/tag/android-v9.5.2, is this just taken from the platform/android/changelog.md file if that one exists?

**Comment by wipfli** [comment]
Hm that file did not get updated it seems... https://github.com/maplibre/maplibre-gl-native/blob/2fcd4f8dea87a43efd561128396dfec08f463a70/platform/android/CHANGELOG.md?plain=1#L1-L12

**Comment by wipfli** [comment]
`git log --oneline -- platform/android` gives this:

```
d129432ce Bump semver from 7.3.7 to 7.3.8 in /platform/android (#530)
53207c456 Removing unused versions sdk (#515)
58543a791 Fixes potential NaN when calling `NativeMapView::nativeMoveBy` (#501)
b567d466e Upgrade Gradle from 3.6.3 to 3.6.4 (#456)
39574ed23 (tag: node-v5.0.1-pre.0) Upgrade libs and remove Jetifier (#218)
1310ce298 Fix android ci workflows (#476)
d209c4f5b Bump to JDK 11 in android CI and generate Gradle Wrapper (#474)
485422634 Bump ejs from 3.1.7 to 3.1.8 in /platform/android (#470)
e147b11fd Bump semver from 5.7.1 to 7.3.7 in /platform/android (#461)
f4f7232b0 Bump pixelmatch from 4.0.2 to 5.3.0 in /platform/android (#460)
793a5193f Bump esm from 3.1.0 to 3.2.25 in /platform/android (#463)
3e98f60ef Migrate examples in android TestApp to Kotlin (#416)
1341f33ba Add ClientOptions to be able to pass around client name and version (#365)
acdce04a2 Use maplibre docs for more links (#354)
6bbeb9fd9 Use the MapLibre style spec docs website (#353)
5f679b55b Refresh iOS & Android build docs
a1f3dd263 Bump ejs from 2.7.4 to 3.1.7 in /platform/android (#299)
eca80dbc0 Replace Mapbox with MapLibre in README titles (#297)
32ed70c95 [msvc] Fix warnings, mainly casting to smaller types (#270)
d9a22ba2c Changed missed MapBox reference to MapLibre (#253)
ea234edf6 chore: rename master -> main in CI and scripts (#246)
b7a42e997 Remove obsolete CI configurations (#219)
b8b2b80a1 Bump lodash from 4.17.19 to 4.17.21 in /platform/android (#195)
381e43fe3 (tag: ios-v5.12.2, tag: android-v9.5.2) Updating changelogs for release ios-v5.12.2 and android-v9.5.2

```

**Comment by wipfli** [comment]
And `git log --oneline -- src include` gives this:

``` 
2b26632ee Add missing header guards (#543)
c72c468ff Fix typo in geo.cpp (#412)
1341f33ba Add ClientOptions to be able to pass around client name and version (#365)
52b5f02ed Fix render tests (#351)
9cd70bfe7 Qt build improvements and documentation (#277)
7e133e3bd fix shiftY calculation typo (#285)
32ed70c95 [msvc] Fix warnings, mainly casting to smaller types (#270)
539d81a3b Rename MaptilerFileSource to MBTilesFileSource (#198)
87bb49250 Fix street label appearance while animating near zoom level threshhold (#267)
6db27f50a Implement map projection functionality (#254)
cfcbc62fa Feature - Bring back node support (#217)
135dca679 Fix incorrect brackets in 'toGeometryCoordinate' (#174)
811b18b74 [win] Additional fixes for MSVC and MinGW (#142)
340f3d6cd add missing include to fix error: ‘exception_ptr’ in namespace ‘std’ does not name a type (#172)
cae0fc272 Compression (#147)
2646f9c41 Add additional 'toString' specialisation (#140)
fe041b80c [msvc] Fix compilation errors and warnings (#141)
8b804a190 maplibre support for Qt6 and MSVC 2019 (#125)
1ce3a4b07 [core] fix perf regression in cached tiles of tile pyramid (#129)
6be1249a1 [qt] Update for tile server configuration changes (#102)
b76136178 Fix: invalid tile url template for MapLibre style (#107)
d62ff400c (tag: macos-v0.19.0, tag: ios-v5.12.0, tag: android-v9.5.0) Replacing hardcoded configuration with configurable API and removing Mapbox assets  (#90)
```

**Comment by wipfli** [comment]
The build step in `android-release.yml` did not succeed:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':MapboxGLAndroidSDK:compileReleaseKotlin'.
> Could not resolve all artifacts for configuration ':MapboxGLAndroidSDK:releaseCompileClasspath'.
   > Could not download okhttp-3.12.3.jar (com.squareup.okhttp3:okhttp:3.12.3)
      > Could not get resource 'https://repo.maven.apache.org/maven2/com/squareup/okhttp3/okhttp/3.12.3/okhttp-3.12.3.jar'.
         > Could not GET 'https://repo.maven.apache.org/maven2/com/squareup/okhttp3/okhttp/3.12.3/okhttp-3.12.3.jar'.

            > Read timed out
   > Could not download gson-2.8.6.jar (com.google.code.gson:gson:2.8.6)
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
      > Could not get resource 'https://repo.maven.apache.org/maven2/com/google/code/gson/gson/2.8.6/gson-2.8.6.jar'.
Use '--warning-mode all' to show the individual deprecation warnings.
         > Could not HEAD 'https://repo.maven.apache.org/maven2/com/google/code/gson/gson/2.8.6/gson-2.8.6.jar'.
See https://docs.gradle.org/6.4.1/userguide/command_line_interface.html#sec:command_line_warnings
            > Read timed out
```

**Comment by wipfli** [comment]
Hm I wonder why the release build fail. Currently, we have at lease three workflows that potentially build android:

* `android-ci.yml` (last successful run 2 years ago)
* `android-ci-pull.yml` (last successful run today)
* `android-release.yml` (last successful run 1 year ago)

**Comment by wipfli** [comment]
Maybe `make apackage` is something we do in `android-ci.yml`?

**Comment by thehoneymad** [comment]
@wipfli is up doing stuff I see. :D

**Comment by wipfli** [comment]
`make apackage` works in docker on my ubuntu laptop with the following steps:

```
docker run --rm -it ghcr.io/maplibre/android-ndk-r21b
git clone https://github.com/maplibre/maplibre-gl-native.git --recursive --depth 1
cd maplibre-gl-native/platform/android/
make apackage
```

So maybe the timeout above was just a network problem with the GitHub runner...

**Comment by wipfli** [comment]
Re-running the release action: https://github.com/maplibre/maplibre-gl-native/actions/runs/3660654651/jobs/6192548596

**Comment by wipfli** [comment]
This time the `make apackage` step worked. The release failed now at "generate javadoc" with the following error message:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':MapboxGLAndroidSDK:javadocrelease'.
> Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): '/__w/maplibre-gl-native/maplibre-gl-native/platform/android/MapboxGLAndroidSDK/build/tmp/javadocrelease/javadoc.options'
```

**Comment by wipfli** [comment]
Locally, also the `make android-javadoc` step works for me with:

```
docker run --rm -it ghcr.io/maplibre/android-ndk-r21b
git clone https://github.com/maplibre/maplibre-gl-native.git --recursive --depth 1
cd maplibre-gl-native/platform/android/
make android-javadoc
```

**Comment by wipfli** [comment]
Rerunning... https://github.com/maplibre/maplibre-gl-native/actions/runs/3660654651/jobs/6192919945

**Comment by wipfli** [comment]
The good thing is that at least the library and documentation builds locally. So now we only need to get it to build in the runners. And then we need to push out the release artifacts to GitHub Releases and Maven.

Regarding Maven, the `android-release.yml` workflow uses a bunch of interesting secrets:

* `GPG_KEY_CONTENTS`
* `OSSRH_USERNAME`
* `OSSRH_PASSWORD`
* `SIGNING_KEY_ID`
* `SIGNING_PASSWORD`
* `SONATYPE_STAGING_PROFILE_ID`

6 things to just publish to one place, this is horrible. Now I understand why NPM gives you an auth token with which you can upload releases...

**Comment by wipfli** [comment]
This is related to the old idea of documenting what secrets we have: https://github.com/maplibre/maplibre-gl-native/issues/312

**Comment by wipfli** [comment]
Failed again in the `make apackage` step:

```
FAILURE: Build failed with an exception.

> Task :MapboxGLAndroidSDK:compileReleaseKotlin FAILED
* What went wrong:
Execution failed for task ':MapboxGLAndroidSDK:compileReleaseKotlin'.
> Could not resolve all artifacts for configuration ':MapboxGLAndroidSDK:releaseCompileClasspath'.
   > Could not download okhttp-3.12.3.jar (com.squareup.okhttp3:okhttp:3.12.3)
      > Could not get resource 'https://repo.maven.apache.org/maven2/com/squareup/okhttp3/okhttp/3.12.3/okhttp-3.12.3.jar'.
         > Could not GET 'https://repo.maven.apache.org/maven2/com/squareup/okhttp3/okhttp/3.12.3/okhttp-3.12.3.jar'.
            > Read timed out
```

**Comment by wipfli** [comment]
Rerunning: https://github.com/maplibre/maplibre-gl-native/actions/runs/3660654651/jobs/6193312555

**Comment by boldtrn** [comment]
Github Actions do have a spotty network connection at times :( - we have similar issues for CI tests that require a connection, they randomly fail sometimes.

**Comment by wipfli** [comment]
And yet another run now hopefully without timeouts... https://github.com/maplibre/maplibre-gl-native/actions/runs/3664281356/jobs/6194598660

**Comment by wipfli** [comment]
Yeah this is disappointing. Some people in https://github.com/actions/runner-images/issues/1499 seem to just have switched to self-hosted runners...

**Comment by wipfli** [comment]
Timed out again...

**Comment by boldtrn** [comment]
A self hosted runner in a public repo seems to be discouraged, but maybe we have to go down that path and only run this on the main branch to avoid running malicious code?

**Comment by wipfli** [comment]
The container registry personal access token `CR_PAT` is actually not needed in the android-release.yml workflow. Because the container is public and the workflow only needs to read the container...

https://github.com/maplibre/maplibre-gl-native/blob/73973703426ebf11c3c6bea60857644c44d7b5e5/.github/workflows/android-release.yml#L12-L16

**Comment by wipfli** [comment]
I would really want to avoid self-hosted runners as far as we can, because:

* Maintaining the runners is extra work which is often done manually. And everything we do not have in code will be lost from our collective knowledge on a one year timescale, as this issue around make a release nicely shows
* Uses financial resources which I would rather want to allocate to compensate people
* Makes it hard for contributors to have the identical setup in their forks for development

**Comment by wipfli** [comment]
I am now messing around with the workflow and timeout settings in my fork at https://github.com/wipfli/maplibre-gl-native/actions/runs/3665108379/jobs/6195967319

**Comment by wipfli** [comment]
If this ever gets to the firebase step I will let you know..

**Comment by wipfli** [comment]
It would be great if I could run the `release-android.yml` workflow locally. Does something like that exist?

**Comment by wipfli** [comment]
What I do at the moment is go though the individual steps and copy-paste them to my console...

**Comment by wipfli** [comment]
What is the difference between graddlew and mvn anyway?

**Comment by boldtrn** [comment]
> What is the difference between graddlew and mvn anyway?

Gradle is Androids default built system. We might have to try the Gradle settings instead, good point 👍 - essentially Gradle and Maven work very similar, you define your build, plugins, dependencies, etc. and use the tool to build.

**Comment by wipfli** [comment]
Thanks @boldtrn

**Comment by wipfli** [comment]
I keep reading that azure closes idle connections, and that gradle then crashed or so... https://github.com/gradle/gradle/pull/19196 seems to have implemented a 3 minutes timeout in gradle

**Comment by wipfli** [comment]
https://github.com/gradle/gradle/issues/14951

**Comment by wipfli** [comment]
Maybe we should just update our gradle version?

**Comment by wipfli** [comment]
Is this the place where the gradle version is defined?
https://github.com/maplibre/maplibre-gl-native/blob/82732b6e9d7770ef832be080c20414ce517b1486/platform/android/build.gradle#L12

**Comment by boldtrn** [comment]
There is also here: https://github.com/maplibre/maplibre-gl-native/blob/82732b6e9d7770ef832be080c20414ce517b1486/platform/android/gradle/wrapper/gradle-wrapper.properties

If you are using Android Studio, they have an update utility, that makes updating the gradle version very straight forward. https://developer.android.com/studio/build/agp-upgrade-assistant

**Comment by wipfli** [comment]
Hm updating gradle alone does not seem to solve the issue. I run android-release.yml with @artakka's pull request #593 in https://github.com/wipfli/maplibre-gl-native/actions/runs/3683508057/jobs/6232164989 but it just gave the usual timeout... This used gradle v6

**Comment by wipfli** [comment]
I think the java version is not the problem for the failing `make android-javadoc`. Instead, I have noticed that the android-release.yml workflow actually checks out the repo at the latest git tag starting with `android-`. So this brings us actually back in time to the last release... The script doing this is called  scripts/ensure-code-revision.sh

**Comment by wipfli** [comment]
After more back and forth I am convinced now that `make android-javadoc` fails because of Java 11. Here is a debug run in my fork where I had a look after which step the javadoc fails:

<a href="https://github.com/wipfli/maplibre-gl-native/actions/runs/3702117524/jobs/6272040674"><img src="https://user-images.githubusercontent.com/53421382/207808661-2d925bcc-7a58-4745-96b8-08f8066c3125.png" width=300></a>

I think we should build the javadocs as part of `android-ci-pull.yml` such that we make sure that we can actually build the docs...

**Comment by wipfli** [comment]
I also had a look if #596 resolves the problem, but it seems it does not...

**Comment by wipfli** [comment]
Let's debug the javadoc stuff in https://github.com/maplibre/maplibre-gl-native/pull/603

**Comment by boldtrn** [comment]
I had weird Javadoc errors in maplibre-nav as well and could not find the source for these... really weird.

**Comment by wipfli** [comment]
If we use Java 8 or whatever the version is in the docker container in the android-release.yml workflow, i.e., if we comment out the install java 11 part, then everything works and I was able to publish to my github releases in my fork. I think there is a good chance that the maven publishing still works too.

However, it only works on java 8 before the gradle plugin update in https://github.com/maplibre/maplibre-gl-native/pull/611.

I think it would be valuable to make a release before we update too many things.

What should I do now? Revert #611, and make an android release, then add #611 again? Create a separate branch before #611 and publish from there? Or maybe fix the `make android-javadoc` in java 11 and make a release from where we are now?

**Comment by wipfli** [comment]
My preferred option would be to temporarily revert #611...

**Comment by wipfli** [comment]
Running the release now on a self-hosted runner. Let's see how far it gets...

https://github.com/maplibre/maplibre-gl-native/actions/runs/3726309604/jobs/6319668919

**Comment by wipfli** [comment]
Crashed in the firebase step. It was able to log in but then did not succeed. I think we can just disable the firebase device test for now...

**Comment by wipfli** [comment]
https://github.com/maplibre/maplibre-gl-native/pull/616

**Comment by wipfli** [comment]
I changed the commit attached to tag `android-v9.6.0`. If you have recently pulled maplibre-gl-native, this might lead to some errors...

**Comment by wipfli** [comment]
The workflow succeeded but I am not sure if it created a maven release: https://mvnrepository.com/artifact/org.maplibre.gl/android-sdk

**Comment by fynngodau** [comment]
I am able to download 9.6.0 from mavenCentral :+1: thank you!

**Comment by wipfli** [comment]
Ah really, that is great! So maybe the mvnrepository.com website just needs a bit of time...

**Comment by fynngodau** [comment]
Yes, it's working flawlessly as far as I can tell, will be happy to report any issues though :) great work!

**Comment by wipfli** [comment]
Android v9.6.0 is now also on the maven website at https://mvnrepository.com/artifact/org.maplibre.gl/android-sdk/9.6.0. Closing this one...
