### ISSUE TITLE
Android debugging

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-native#604]
How can we locally debug changes in Android and make sure the CI will pass when we submit a pull request?

**Comment by wipfli** [comment]
Local docker container is maybe an option.

Clone and start docker:
```
git clone git@github.com:maplibre/maplibre-gl-native.git
cd maplibre-gl-native
git submodule update --init --recursive
cd ..
docker run --rm -it -v "$(pwd)/maplibre-gl-native":/src ghcr.io/maplibre/android-ndk-r21b
```

**Comment by wipfli** [comment]
Install java 11 seems to work with these steps taken from https://docs.azul.com/core/zulu-openjdk/install/debian, but let me note that it is a bit absurd to install stuff in a docker container...

```
sudo apt-get -q update
sudo apt-get -yq install gnupg curl 
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0xB1998361219BD9C9
curl -O https://cdn.azul.com/zulu/bin/zulu-repo_1.0.0-3_all.deb
apt-get install ./zulu-repo_1.0.0-3_all.deb
apt-get update
apt-get install zulu11-jdk
```
gives us
```
root@82f58ad508ee:/src# java -version
openjdk version "11.0.17" 2022-10-18 LTS
OpenJDK Runtime Environment Zulu11.60+19-CA (build 11.0.17+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.60+19-CA (build 11.0.17+8-LTS, mixed mode)
```

**Comment by thehoneymad** [comment]
> How can we locally debug changes in Android and make sure the CI will pass when we submit a pull request?

@wipfli I am missing a little context here. 

1. What kind of changes are you talking about? Any code change?
2. Are you also speaking toward step debugging with a debugger?

I had some thoughts about reproducing a local build. Here are my points:
1. I think for general build, test, and debug where we rely on local dependencies for JDK and NDK, we should rely on pure `gradle`. `gradle` is native to any Java and Android builder and it requires limited boot time with `gradle build` and `gradle test`. A local build *should* fail if it can not find the right JDK and NDK dependencies.
2. For mimicking the CI build, we can use something like `https://github.com/nektos/act`.

And all of these should go into the dev guide. :)

**Comment by wipfli** [comment]
With debugging I meant reproducing the problems we have in CI and not break points etc...

**Comment by louwers** [comment]
Related: #622

**Comment by artakka** [comment]
Most of my problems are from the ktlint and formatting the text. I run
ktlint locally and fix the issues. We should either disable the formatting
checks or make Android Studio automatically format the files the way ktlint
likes them.

**Comment by louwers** [comment]
Yes I ran into that issue as well. Let me create an ticket out of that.

**Comment by louwers** [comment]
Once the new CI is merged, you will be able to use the Nix-based Docker image, or a Nix-based environment or the GitHub Actions environment.
