### ISSUE TITLE
Java version strategy

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-native#606]
In CI, we use java 11 which dates back to 2018 if I am not mistaken, see https://www.oracle.com/java/technologies/java-se-support-roadmap.html

What should be our strategy for the java version? Update as soon as a new one is generally available?

**Comment by wipfli** [comment]
I have java 17 installed on my laptop and it is a bit frustrating for me that basically all commands fail if I do something like `cd platform/android && make android-check` for example. How do people solve this problem usually? Is there something like NVM for java?

**Comment by birkskyum** [comment]
Most of these tools are unfortunately mac/linux only (sdkman / jenv etc.). A common solution in this day and age is using the Java->Kotlin auto-transpiler in android studio to move on.

**Comment by artakka** [comment]
I will switch all Java to  Kotlin soon

**Comment by louwers** [comment]
Java 17 will be used available / used on CI soon.
