### ISSUE TITLE
Documenting the android docker build

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-native#622]
We have docker containers for building the Android package but I am not sure that we have documentation on how to update and generate the docker containers.

The containers are stored in the github container registry at the MapLibre org level at https://github.com/orgs/maplibre/packages

We have:

* android-ndk-r21b
* android-base

Linux builder is probably for Qt, right @ntadej?

Let's document how we can update the docker images for the android builds...

**Comment by wipfli** [comment]
The docker files are located in platform/android/docker:

https://github.com/maplibre/maplibre-gl-native/blob/d11df0066e258cf798594448fcb3eb784bf8e348/platform/android/docker/android-base#L1-L2

**Comment by wipfli** [comment]
To close this issue, I think we should document how to update the docker stuff in platform/android/README.md

**Comment by wipfli** [comment]
We have github actions workflows to generate the docker images and upload them to the container registry.

The workflow has a manual trigger:

https://github.com/maplibre/maplibre-gl-native/blob/d11df0066e258cf798594448fcb3eb784bf8e348/.github/workflows/android-docker-ndk-r21b.yml#L1-L3

And it uses the `CR_PAT` GitHub secret, which I think stands for "container registry personal access token":

https://github.com/maplibre/maplibre-gl-native/blob/d11df0066e258cf798594448fcb3eb784bf8e348/.github/workflows/android-docker-ndk-r21b.yml#L19-L21

But I don't know if this access token still works. Only the people from the MapLibre Governing Board and I have write access at the moment to the maplibre github org level at the moment.

**Comment by louwers** [comment]
Helpful advice from @wipfli: do an Android release once this ticket has been completed to ensure that it (still) goes smoothly.
