### ISSUE TITLE
The 'kotlin-android-extensions' Gradle plugin is deprecated.

### ISSUE THREAD

**Issue by artakka** [maplibre/maplibre-gl-native#626]
**Describe the bug**
The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.

**To Reproduce**
Build the SDK module

**Comment by louwers** [comment]
I don't think kotlinx.android.parcel.Parcelize is being used.
