### ISSUE TITLE
how to Generate png from our own mbtiles file

### ISSUE THREAD

**Issue by toqeer786** [maplibre/maplibre-gl-native#640]
i am using ubuntu 20 and completed All the steps related to linux and also your instruction about style. json ,, i had generated png from your zurich_switzerland.mbtiles but when i want to generates pngs it gives me error ,,
my question is simple can we generate pngs from mbtiles(vector) files ???
kindly check the error below and guide me how we can generate pngs in folder sub folder form

""
sudo ./build/bin/mbgl-render --style style1.json --output out2.png
[sudo] password for ubuntu: 
[WARNING] {mbgl-render}[ParseStyle]: source must have tiles
Error: Layer 'landuse_classes' is not compatible with source 'openmaptiles'

""

**Comment by acalcutt** [comment]
Are you following the "Using your own style/tiles" section of https://github.com/maplibre/maplibre-gl-native/tree/main/platform/linux ?

My guess for "Error: Layer 'landuse_classes' is not compatible with source 'openmaptiles'" would be the mbtiles you specified does not have a layer your style references.

**Comment by OmarShehata** [comment]
@toqeer786 if you're still having trouble, can you share the file `style1.json` so we can help point you in the right direction?

**Comment by louwers** [comment]
Please take this to [GitHub Discussions - Q&A](https://github.com/maplibre/maplibre-gl-native/discussions/categories/q-a). Thanks!
