### ISSUE TITLE
Replace mapbox watermark on the maps with maplibre

### ISSUE THREAD

**Issue by artakka** [maplibre/maplibre-gl-native#643]
**Describe the bug**
The watermark icon on the bottom left of the maps says Mapbox

**Platform information (please complete the following information):**
 - OS: Android
![Screenshot_20221228-213534](https://user-images.githubusercontent.com/180515/209900225-6d8feb93-307d-4090-b0f8-b92e5c2c0711.png)

**Comment by louwers** [comment]
This seemed like a good first issue.

Maybe a colorless logo like in the style of Mapbox? Or something more colorful?

![maplibre-logo](https://user-images.githubusercontent.com/649392/210396698-c317d886-3616-4ce5-9ac0-fdab97519402.png)

**Comment by wipfli** [comment]
We changed the logo in MapLibre GL JS. Probably you find the relevant assets there somewhere...

**Comment by acalcutt** [comment]
When does the logo show in maplibre-native? is it like the old behavior where it only shows when a mapbox source is used?

**Comment by louwers** [comment]
Found the issue. https://github.com/maplibre/maplibre-gl-js/pull/786

**Comment by acalcutt** [comment]
At least that is close to the current js behavior, where it is an option now.

**Comment by ntadej** [comment]
Well, I guess the watermark represents the source of the maps and not necessarily the engine used. Not sure we need MapLibre logo there (licensing afaik does not require it). Maybe we should make it configurable to display an arbitrary logo.

**Comment by louwers** [comment]
It can be enabled and disabled it seems: https://maplibre.org/maplibre-gl-native/android/api/

The logo: https://github.com/maplibre/maplibre-gl-js/blob/84499986d3e9f0d6163aa35083c54cda01b0097b/src/css/svg/maplibregl-ctrl-logo.svg

> Maybe we should make it configurable to display an arbitrary logo.

Good idea, let me replace it with the MapLibre logo for now, and then we create a new ticket for this?

**Comment by acalcutt** [comment]
Is this logo out of date because maplibre-native points to an older maplibre-gl-js release in the root directory?

**Comment by louwers** [comment]
Good catch! But it is still the same.
