### ISSUE TITLE
Ionic framework turn by turn navigation

### ISSUE THREAD

**Issue by bmarcco** [maplibre/maplibre-gl-native#66]
Hi, I am working on a navigation application in Ionic (Angular), OpenStreetMap and I use Valhalla as a routing machine, now I wonder if there is a possibility to get navigation similar to the image below?
![115017358-b7cf8880-9eb6-11eb-9b75-cb46a2a0ccfa](https://user-images.githubusercontent.com/63052506/115048648-10fce380-9eda-11eb-8b12-aee4baa3b0be.png)

**Comment by reezer** [comment]
You can use a corresponding Mapbox Navigation version with MapLibre. I got this to work using a Podspec like the following:

```
# Mapbox-iOS-SDK.podspec
Pod::Spec.new do |s|
	s.name = 'Mapbox-iOS-SDK'
	s.version = '5.9.0'
	s.license = { :type => 'Unspecified' }
	s.homepage = 'https://github.com/maplibre/'
	s.authors = { 'MapLibre' => '' }
	s.summary = 'Pretending to be MapBox when we are not'
	s.platform = :ios
	s.source = {
		:http => 'https://github.com/maptiler/maplibre-gl-native/releases/download/ios-v5.11.0/Mapbox-5.11.0.zip' # Change version to the latest
	}
	s.ios.deployment_target = '10.0'
	s.ios.vendored_frameworks = 'Mapbox.xcframework'
end
```

Maybe something like this could be added to the Maplibre repo or created in a separate one?

Once done you can use these entries in your Podfile:

```
    pod 'Mapbox-iOS-SDK', :git => 'ssh://git@github.com:maplibre/maplibre-pod.git' # This repo does not exist, just an example, what it would like if that's a repo containing the above podspec.
    pod 'MapboxNavigation', '~> 0.40.0'
```

Maybe it would make sense to also create a Maplibre fork for Navigation? I guess that would be a separate Issue though.

In case anyone reads this: Please keep in mind that you want to remove any cached versions of Mapbox in both your Pods directory and the cache directory, or else you might easily end up using the original Mapbox code.

**Comment by wipfli** [comment]
@reezer is https://github.com/maplibre/maplibre-navigation-android what you were thinking about?

**Comment by reezer** [comment]
What I described was merely a way to use an old Mapbox Navigation version.

However, if there would be a Maplibre Navigation for iOS that would be amazing.

**Comment by louwers** [comment]
Navigation is out of scope for MapLibre GL Native (in this repo) currently.

Please use the the repo @wipfli linked at or https://github.com/maplibre/maplibre-navigation-ios for iOS.
