### ISSUE TITLE
Add to docs info on how to build and deploy to attached hardware iOS device.

### ISSUE THREAD

**Issue by hallahan** [maplibre/maplibre-gl-native#725]
When building an iOS project in Xcode, we can run in the simulator without any extra configuration. For attached hardware, however, we have to explicitly check `Automatically manage signing`, otherwise Xcode will try to deploy with an old Mapbox Team provisioning profile ID.

**Describe the solution you'd like**
Either explain to the user to check the box or fix the xcproject to just use a default provisioning profile.

<img width="633" alt="Screenshot 2023-01-23 at 1 46 06 PM" src="https://user-images.githubusercontent.com/556367/214434612-53c2dabe-ae89-49e8-b75d-481e771a4006.png">

**Comment by louwers** [comment]
@hallahan Could you remove the old Mapbox Team provisioning profile ID in a PR?

**Comment by hallahan** [comment]
About to PR a fix with instructions.

<img width="856" alt="code-sign" src="https://user-images.githubusercontent.com/556367/214957613-2d565b1a-6590-495e-8979-2022096e02f1.png">
