### ISSUE TITLE
Disable warnings 'warning: ignoring ‘#pragma mark ’'

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-gl-native#730]
`#pragma mark` is used througout the codebase for [XCode](https://stackoverflow.com/questions/6853821/what-is-the-significance-of-pragma-marks-why-do-we-need-pragma-marks).

They should be removed or ignored when compiling with gcc.

```
/home/bart/src/maplibre-gl-native/src/mbgl/map/transform.cpp:46: warning: ignoring ‘#pragma mark ’ [-Wunknown-pragmas]
   46 | #pragma mark - Map View
      | 
/home/bart/src/maplibre-gl-native/src/mbgl/map/transform.cpp:68: warning: ignoring ‘#pragma mark ’ [-Wunknown-pragmas]
   68 | #pragma mark - Camera
...
```

**Comment by louwers** [comment]
We can change them into comments. 

https://www.avanderlee.com/xcode/xcode-mark-line-comment/

But I don't think adding/keeping IDE specific comments or pragma's to the core is a good idea.

**Comment by ntadej** [comment]
> But I don't think adding/keeping IDE specific comments or #pragmas to the core is a good idea.

Not sure I agree with that. I think the most commonly used IDEs could be supported, as long as they do not cause issues in general. So we should remove the pragmas, but keeping comments would be useful.
