### ISSUE TITLE
Update the test app to demo the Annotations plugin from maplibre-plugins-android 

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-gl-native#741]
The test app uses deprecated functionality from the Android SDK to show Annotations: https://github.com/maplibre/maplibre-gl-native/tree/main/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation

Rewrite this so that it works with the Annotations plugin from [maplibre-plugins-android](https://github.com/maplibre/maplibre-plugins-android). Also make a PR to this repo to link to the new code in the example app, along with some samples in the [`README.md` of plugin-annotation](https://github.com/maplibre/maplibre-plugins-android/tree/main/plugin-annotation).

**Comment by wipfli** [comment]
Can you add a link to the Bounty Direction tracking issue in maplibre/maplibre?

**Comment by louwers** [comment]
This ticket now has a small bounty in the documentation bounty direction: [#191](https://github.com/maplibre/maplibre/issues/191).

**Comment by fynngodau** [comment]
> The test app uses deprecated functionality from the Android SDK to show Annotations. Rewrite this so that it works with the Annotations plugin from [maplibre-plugins-android](https://github.com/maplibre/maplibre-plugins-android)

Are you aware that [maplibre-plugin-annotations](https://github.com/maplibre/maplibre-plugins-android) itself contains a different sample app that makes use of its own functionality? Therefore it may not make sense to rewrite the MapLibre SDK sample app – instead we could mark deprecated features as deprecated inside the app, and add a note that developers should also look at the plugin sample app.

**Comment by louwers** [comment]
@fynngodau That also sounds like a good option to me!

**Comment by louwers** [comment]
Closing this one in favor of #810.
