### ISSUE TITLE
Schedule meeting with Alan to discuss MapLibre contributions and possible roadblocks

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-gl-native#758]
@alanchenboy from [GrabMaps](https://www.grab.com/sg/enterprise-blog/grabmaps/) has been making code contributions to MapLibre. We want to schedule a meeting and define what should be part of the [Milestone to upstream GrabMaps' bugfixes](https://github.com/maplibre/maplibre-gl-native/milestone/11).

**Comment by louwers** [comment]
Meeting set for 9 Feb 9:00 - 10:00 (CET), 16:00 - 17:00 (UTC+8)

**Comment by alanchenboy** [comment]
-_- Glad to be a contributor.
