### ISSUE TITLE
Publish C++ API and inline documentation with Doxygen

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-gl-native#759]
The C++ API and inline documentation should be published to make it more easliy accessible.

Doxygen (still) seems to be king for C++, but if anyone knows any alternatives I am happy to take a look.

**Comment by birkskyum** [comment]
That would be cool. There is the Doxygen / Sphinx / Breathe / Exhale combo that might be relevant here.

**Comment by louwers** [comment]
Do you know if this stack uses reStructuredText? I am personally not a big fan of it and for a lot of people it would be another thing to learn.

Does not look like it is needed:

https://exhale.readthedocs.io/en/latest/quickstart.html?highlight=markdown#do-i-have-to-write-restructuredtext

**Comment by birkskyum** [comment]
Exhale takes Doxygen XML documentation and generates reStructuredText, so no reStructuredText has to be written

**Comment by louwers** [comment]
@birkskyum Do you want the private API to be documented as well? Or just the public C++ API.

**Comment by birkskyum** [comment]
I think the public api will suffice for now - would it be helpful from a maintenance standpoint to have the private api Publisher?

**Comment by louwers** [comment]
@birkskyum Not so much I think. Especially contributors will probably want to look at the source code.
