### ISSUE TITLE
Map opens "zoomed in" when app brought to foreground with `metal-support` -branch

### ISSUE THREAD

**Issue by juhieta** [maplibre/maplibre-gl-native#76]
Using iOS SDK built from the `metal-support` -branch, map opens "zoomed in" when bringing front from background, and then updates to correct zoom level. This causes visible flickering.

This doesn't happen with SDK built from master.

# Steps to reproduce
1. Start iOS SDK [demo application](https://github.com/maplibre/maplibre-gl-native/tree/master/platform/ios/platform/ios/app) built from `metal-support` -branch
2. Move app to background (don't close it)
3. Click app icon to bring back to foreground

# Expected behavior
Map opens to correct zoom level without flickering

# Actual behavior
Map opens zoomed in, then quickly shows actual zoom level causing flicker.

Following is a video showing the issue with the iOS SDK Demo App, first in normal speed and then slowed down for better view:

https://user-images.githubusercontent.com/2369584/115957491-7e78c780-a50b-11eb-9589-ade706062091.mov

# Configuration
Maplibre iOS SDK version: `metal-support` -branch commit [bae8d18](https://github.com/maplibre/maplibre-gl-native/commit/bae8d18d5e04651177183c34f869bde7d55c32cb)
iOS/macOS versions: **iOS 14.4**
Device/simulator models: **iPhone 11 Simulator**
Xcode version: **12.4**

**Comment by juhieta** [comment]
This problem can be fixed with PR #83

**Comment by juhieta** [comment]
Was fixed with #83

**Comment by juhieta** [comment]
Reopening until #83 is merged to metal branch

**Comment by petr-pokorny-1** [comment]
> Reopening until #83 is merged to metal branch

@juhieta  I've merged #83 into metal branch, are we good to close this one?

**Comment by juhieta** [comment]
> > Reopening until #83 is merged to metal branch
> 
> @juhieta I've merged #83 into metal branch, are we good to close this one?

Great, thanks and let's close! 👍
