### ISSUE TITLE
Define plan for Android instrumentation tests

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-gl-native#761]
The Android CI is failing due to a problem with the instrumentation tests: https://github.com/maplibre/maplibre-gl-native/actions/runs/4056188076/jobs/6980347353

We have MapTiler's credentials configured for Firebase Instrumentation tests. @wipfli mentioned that instead of using Google we can use AWS, since we have an AWS account and they have credits for us. I suggest that I disable the instrumentation tests for now, and that I create another issue for moving the instrumentation tests on AWS.

**Comment by wipfli** [comment]
@artakka @thehoneymad are AWS device farm tests of interest to you?

**Comment by louwers** [comment]
@artakka Aready mentioned it's hugely important that MapLibre runs well on older devices as well.

**Comment by thehoneymad** [comment]
@wipfli it does. I have not deep dived on this yet. Would you like to take the lead to propose a design?

**Comment by thehoneymad** [comment]
Looping @roblabs in. Turns out he has tried the device farm path before.

**Comment by maxammann** [comment]
In other open source projects I'm using https://www.browserstack.com/ successfully.

It's free for OSS and very expensive otherwise :D

**Comment by wipfli** [comment]
> Would you like to take the lead to propose a design?

Probably best if Bart does it

**Comment by ovivoda** [comment]
I saw that the test is reporting device not supported. Do we know if this is the reason why it fails? Who can take a look into firebase account? IE has access?

**Comment by wipfli** [comment]
The friebase account is a left-over from MapTiler. They donated the native repo to MapLibre, but we should not use their Google account anymore for CI. We have some donated AWS credits and should use those for testing. Investing time in the google firebase platform does not seem to make sense if we anyway do not plan to use it afterwards.

**Comment by wipfli** [comment]
Or maybe use browserstack as @maxammann suggested. In any case, Firbase can be safely removed I think.

**Comment by wipfli** [comment]
Secrets and credentials should be documented here: https://github.com/maplibre/maplibre/blob/main/SECRETS.md

**Comment by wipfli** [comment]
Like that, we can have one central place where we understand what logins we have and who you have to ask to get the clear text login. It is a bit outdated, but lets aim to collect all relevant info there.

**Comment by louwers** [comment]
> Secrets and credentials should be documented here: https://github.com/maplibre/maplibre/blob/main/SECRETS.md

Done https://github.com/louwers/maplibre/pull/2
