### ISSUE TITLE
How to support 3D models for both native Android and iOS SDK's ?

### ISSUE THREAD

**Issue by hmtriit** [maplibre/maplibre-gl-native#777]
Hi master,

I want to implement model 3d into map, Please help me  documentation for both platforms that showcases an example of how this is actually supposed to be done. 

Port "antenna building" example from gl-js https://docs.mapbox.com/mapbox-gl-js/example/add-3d-model/

Thanks!!!

**Comment by louwers** [comment]
3D is not supported for MapLibre GL Native yet.

Please see #252
