### ISSUE TITLE
Crash with custom heatmap when zooming in/out the map on Android

### ISSUE THREAD

**Issue by jDilshodbek** [maplibre/maplibre-gl-native#794]
I am using my heatmap which is added to my custom tile from backend.It shows heatmap fine , but when I start zooming in or out with two fingers or with control buttons calling `CameraUpdateFactory.zoomTo` methods on the map. The application is crashing.
I am using maplibre verison 9.6.0 here in dependency 
`implementation 'org.maplibre.gl:android-sdk:9.6.0'`

Hers is the error output in Android Studio:
```
terminating with uncaught exception of type std::runtime_error: paths outside valid range of coordinate_type
Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 29729 (Worker 1), pid 27662
```

**Expected behavior**
Application shouldn't crash when I zoom in or out on the map.

**Screenshots**
![telegram-cloud-photo-size-2-5413638111914739981-y](https://user-images.githubusercontent.com/19223457/218008628-c414551f-473e-4100-9b1d-bbd3c14cb3c3.jpg)

**Platform information (please complete the following information):**
 - OS: [Android 12]
 - Platform [Android]
 - Version [12]

**Additional context**
The crash is not happening If I use  Maplibre version `9.5.0`

**Comment by ovivoda** [comment]
@jDilshodbek thanks for reporting the problem. I will look into this one and get back to you.

**Comment by ovivoda** [comment]
@jDilshodbek I looked a bit into PR's merged between 9.5 and 9.6 releases and I could not identify what could cause the issue. Can you please also try with 10.0.2 and see if this issue is still there?

**Comment by jDilshodbek** [comment]
Yeah, it is working fine with v10.0.2

**Comment by ovivoda** [comment]
Closing this issue as it is now fixed. Let's reopen it if you see the issue again.
