### ISSUE TITLE
Getting Started Guide for MapLibre GL Native for Android

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-gl-native#808]
Make a pull request for a getting started guide with instructions of how to add MapLibre GL Native to an Android project as an end-user. This issue has an associated bounty for the [documentation](https://github.com/maplibre/maplibre/issues/191) bounty direction.

## Deliverables

- Installation should be covered.
- All neccesary code to get the [demotiles](https://demotiles.maplibre.org/) style to show should be included.
- The instructions should show up as a page on our [Dokka](https://kotlinlang.org/docs/dokka-introduction.html) based documentation, which is hosted here: https://maplibre.org/maplibre-gl-native/android/api/
- There should be a screenshot.
- Please don't re-use any guides or tutorials that do not have a permissive license. This might be helpful, which does have a permissive license (so can be used): https://github.com/aws-samples/amazon-location-samples

Dokka docs can be generated using `./gradlew dokkaHtml` in `platforms/android`.

You can start a web server to see the docs with:

```
cd MapboxGLAndroidSDK/build/dokka/html/
python -m http.server
```

**Comment by michael-loc009** [comment]
Hi @louwers . I would like to contribute on this task. Can you assign it me?

**Comment by michael-loc009** [comment]
> Hi @louwers . I wonder if you got the issue below when running the command "./gradlew dokkaHtml".
> 
> ```
>  - Variant 'apiElements' capability com.android.tools.build:gradle:7.4.0 declares a library, packaged as a jar, and its dependencies declared externally:
>               - Incompatible because this component declares an API of a component compatible with Java 11 and the consumer needed a runtime of a component compatible with Java 8
>               - Other compatible attribute:
>                   - Doesn't say anything about org.gradle.plugin.api-version (required '7.6')
> ```

I resolved the issue by reinstalling my local java version from 8 to 11.

**Comment by michael-loc009** [comment]
Hi @louwers . I created a PR #939  for the issue #808. Could you help to review my PR?

**Comment by louwers** [comment]
This bounty can be paid out.

**Comment by michael-loc009** [comment]
Thank you @louwers and @ovivoda very much for giving constructive feedback to support me on this task.

**Comment by LsGis** [comment]
@louwers hi,have you ever run "./gradlew dokkaHtml" to report this error?

FAILURE: Build failed with an exception.
* What went wrong:
'org.gradle.api.file.FileCollection org.jetbrains.kotlin.gradle.tasks.KotlinCompile.getClasspath()'

**Comment by Teodor82** [comment]
Hi! I see this issue has a $100 bounty, but it’s been open for a while.
Is the bounty still active, and is this guide still needed?

If yes, I’m happy to take it and align with the expected scope.
Thanks!

**Comment by louwers** [comment]
@Teodor82 No the issue has been closed for 3 years.

**Comment by Teodor82** [comment]
@louwers Thanks for clarifying — appreciate the update.

If you need help with documentation, fixes, or testing on related areas in the future, feel free to reach out.
Happy to help.

Thanks!
