### ISSUE TITLE
Node arm64 publish issue

### ISSUE THREAD

**Issue by acalcutt** [maplibre/maplibre-gl-native#860]
It seems I introduced an issue in https://github.com/maplibre/maplibre-gl-native/pull/804 . In that PR I changed the arm64 docker process to build inside the current directory instead of copying all files into the docker and just copying libs back.

Because of this change, node_modules from the arm64 build (inside docker) are in the directory when the workflow publish steps try to do an npm ci. Because this folder already exists it gets a bunch of permission issues and the npm install fails.

I am looking for a solution to this now. This didn't show in the ci because it doesn't do these couple extra steps for publishing that the release workflow does.

**Comment by louwers** [comment]
This is fixed now right? :slightly_smiling_face:

**Comment by acalcutt** [comment]
I think we can close this for now. Though I tried to move the ci back to a Debug release to test the swap and it hasn't seemed to perform right side. I moved it back to release build type but the current build it taking forever.

**Comment by louwers** [comment]
Ha! After two hours it is still going. It is not stuck though. 

But I think making a Release build is good.
