### ISSUE TITLE
Set up ARM64 Linux Runner

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-gl-native#870]
We need a ARM64 Linux runner because using QEMU or Docker on macOS is slowing us down.

Ping @acalcutt

**Comment by acalcutt** [comment]
I messed with this a little on my side. I made one of those free t4g instances in my account. The free instance is t4g.small and has 2 cores and 2GB memory. At first I was concerned this wouldn't be enough memory, but in my testing the build worked fine there on the apt-packages got installed.

![image](https://user-images.githubusercontent.com/3792408/222451231-154c21fb-67bf-4374-9620-a7d23e7491f9.png)

I was wondering how this runner would be set up, would it use something docker like this some we can easily change OS/RUNNER_VERSION
https://github.com/shivammathur/setup-php/wiki/Dockerized-self-hosted-runner-on-Linux

**Comment by louwers** [comment]
> Or is the instance throw away enough we would just do the actions runner directly on this machine

We do that for macOS now as well. It is not ideal, but also not a big problem as long as we don't store any senstive data on these machines and we make sure we can set them up easily again. This is why actions need to be triggered manually for first time contributors.

Good to know your test worked, I will set one up today!

**Comment by louwers** [comment]
It is added! Ubuntu 20.04.

It is easy to set up another one later.

![image](https://user-images.githubusercontent.com/649392/222498176-9fc4a2ca-18b3-49e5-bf91-a75a5968b07f.png)

**Comment by acalcutt** [comment]
First issue, It needs git. 

![image](https://user-images.githubusercontent.com/3792408/222502484-d41a47b4-42ee-4072-86f5-c1e0b3b9ce05.png)

**Comment by louwers** [comment]
Ah thanks. ;-)

**Comment by acalcutt** [comment]
I looked at my instance and I seem to have git. I also had trouble with apt-get.

**Comment by louwers** [comment]
My bad, accidentaly used Amazon Linux.

**Comment by acalcutt** [comment]
You must have fixed it, it gets further now. It looks like it needs 'libjpeg-dev'

![image](https://user-images.githubusercontent.com/3792408/222536520-bbe391ab-d28c-4625-be4c-298122778d7e.png)

**Comment by louwers** [comment]
I will add it to the list:

https://github.com/maplibre/ci-runners/blob/arm64-linux-runner/ubuntu.yaml

**Comment by acalcutt** [comment]
I think when doing a Debug release like node-ci does right now actually makes this run out of memory. I tried to change the release type to test that but the last job is stuck.

Testing on my arm64 instance I can build a "release" version, but the debug release gets stuck. I tried adding some swap space to get around it, but the build crashed instead of getting stuck.

**Comment by acalcutt** [comment]
So, my issue after I added swap was space. With this I was able to get the debug build to actually complete on this t4g.small instance

Starting with t4g.small with 15GB storage
```
sudo fallocate -l 2G /swapfile
sudo chmod 600 /swapfile
sudo mkswap /swapfile
sudo swapon /swapfile

git clone --recurse-submodules -j8 https://github.com/maplibre/maplibre-gl-native.git
cd maplibre-gl-native
ccache --clear --set-config cache_dir=~/.ccache
cmake . -B build -G Ninja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10 -DCMAKE_BUILD_TYPE=Debug
cmake --build build -j $(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null)
```
This build successfully with about 1G disk space left

A non-debug release works with 10G disk space and without the added swap. I'm not sure this workflow really needs to be a Debug release (though it may give more information in the ci)

**Comment by louwers** [comment]
Sounds like the t4g.small instance _might_ be a bit too limited for our purposes. I enabled 2GB of swap, let's see!

**Comment by louwers** [comment]
Seems like it ran through (and pretty fast as well)! 🙂 

They have 30GB storage available, but I can increase it a bit if needed, does not make sense to penny pinch there I think.

**Comment by acalcutt** [comment]
I had changed the ci to always run a Release version in, so it would probably work without the swap now. 

I wasn't quite ready to merge https://github.com/maplibre/maplibre-gl-native/pull/873 since I planned on doing the node-release workflow too. I'll make a new PR for that.
