### ISSUE TITLE
Offset the center of the map, when in trackingMode -> follow

### ISSUE THREAD

**Issue by georgbachmann** [maplibre/maplibre-gl-native#900]
**Is your feature request related to a problem? Please describe.**
In my app, kind of similar to the Apple-Maps App e.g., I have some overlay cards that sometimes cover parts of the map, and sometimes don't. So not the center of the visible part of my map is not always the center of the screen, but my map is full-screen. I know that I could resize the map along with the overlay cover, but that just brings to much movement into the app.

So now when I do set `mapView.userTrackingMode = .follow`, the user location will be in the center of the screen and therefore very close to the edge of my overlay card. Making it feel off...

**Describe the solution you'd like**
It would be awesome to have a functionality to offset that center. Like e.g. for the compass, there is `mapView.compassViewMargins` which offsets the compass by a x/y amount of points. Would be awesome to have something similar for the user location. (And being able to animate that change would of course be awesome :)

**Describe alternatives you've considered**
Could also be to respect the `safeAreaInsets` of an UIView, but I guess a solution that would then also properly work for Android would be preferable?!?

**Comment by ovivoda** [comment]
This is an interesting proposal. I think it would be useful in various use-cases.

I'm not sure something like this can be achieved with the current API's, unless someone knows another way.

cc @sjg-wdw @alexcristici

**Comment by sjg-wdw** [comment]
I'm not familiar with the current restrictions on center placement.  Seems like a reasonable request and other toolkits do similar things.
It's outside the scope of the current modularization/metal effort, I'm afraid.

**Comment by georgbachmann** [comment]
@JRWilding not that I am aware of?!? Do you know how that would be possible?

**Comment by JRWilding** [comment]
CameraPosition has a `padding` method that takes 4 doubles (or double[]). We don't use the default location component and have implemented our own user tracking, but if you can hook into where the camera gets updated with the new position, you can add padding equal to your overlaid panel's height.

**Comment by georgbachmann** [comment]
@JRWilding sorry for asking again, but I just can't find it. Is this what you mean? https://docs.mapbox.com/android/maps/api/9.6.0/?com/mapbox/mapboxsdk/camera/CameraPosition.html

**Comment by georgbachmann** [comment]
HA!!! Super cool. It seems on iOS there's a property `contentInset` which I haven't seen which seems to do exactly that!
Thanks for pointing that out @JRWilding !
The property you were referring is documented here? https://docs.mapbox.com/android/maps/api/9.6.0/?com/mapbox/mapboxsdk/camera/CameraPosition.html
Is that correct? Just for reference if anybody else stumbles upon that issue here.
