### ISSUE TITLE
Link Codecov to repo

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-gl-native#934]
After logging in you should see `maplibre/maplibre-gl-native`. I don't see it because I am not in the maplibre GitHub organization.

https://app.codecov.io/

You need to set the `CODECOV_TOKEN` as a repo secret and configure the GitHub application (instructions provided).

After that I will take it from there intergrating it in the workflows.

**Comment by ntadej** [comment]
I think tokens are not needed for opensource application so we should not use them.
