### ISSUE TITLE
Create iOS size test

### ISSUE THREAD

**Issue by alexcristici** [maplibre/maplibre-gl-native#943]
Investigating a way to measure the size of the framework after being linked to the demo app.

**Comment by louwers** [comment]
@alexcristici on Slack

> Regarding the size test, I see 2 tests:
> 1 Building the dynamic iOS target to generate the framework, the size now is around 5.5 Mb
> 2 Archive and distribute the iosapp and check the app-thinning.plist , compressed and uncompressed sizes

**Comment by roblabs** [comment]
> @wipfli Can we sign up for the Apple Developer Program as MapLibre? https://developer.apple.com/programs/enroll/

_potential_ 


> [Apple Developer Program Membership Fee Waivers] https://developer.apple.com/support/membership-fee-waiver "Apple Developer Program membership is available at no cost for eligible organizations. Find out if your organization qualifies and how to request a waiver."

**Comment by louwers** [comment]
@roblabs Nice find!

**Comment by wipfli** [comment]
I wrote Open Source Collective, MapLibre's fiscal host, if they can join the Apple Developer Program if they are not part yet. Will keep you updated.

**Comment by wipfli** [comment]
Open Source Collective will not sign us up for the Apple Developer Program, because Apple would give them only one account which they would need to share with all projects.

We have paid now for 1 year a private account for @louwers which I think is good enough for CI. What do you think?

In any case, @louwers please document the CI setup here in readme files in this repository. The credentials itself should be stored in our password manager.

**Comment by ntadej** [comment]
If it helps, I use https://github.com/fastlane/fastlane quite successfully for CI due to automation.

**Comment by louwers** [comment]
@wipfli I will set up the provisioning profile on CI, but I cannot obviously not share my private Apple ID credentials. But I think that is not what you meant.

> Apple would give them only one account which they would need to share with all projects

I think you can set up sub-accounts.

> If it helps, I use [fastlane/fastlane](https://github.com/fastlane/fastlane)

We still need an account enrolled to the Apple Developer Programme.
