### ISSUE TITLE
Source code poorly organized in Xcode

### ISSUE THREAD

**Issue by sjg-wdw** [maplibre/maplibre-gl-native#944]
As a result of the generation of the XCode project for iOS/MacOS the source code lacks the organization we'd normally expect.  Looking through it is kind of a mess.

It's not clear what we can do about this.  Perhaps there are ways to change how it appears in XCode.

**Comment by louwers** [comment]
Related possible solution #840

**Comment by TimSylvester** [comment]
If we're still using CMake, it would help a lot to enable [USE_FOLDERS](https://cmake.org/cmake/help/latest/prop_gbl/USE_FOLDERS.html) and apply [FOLDER](https://cmake.org/cmake/help/latest/prop_tgt/FOLDER.html) to the various sources and/or use [source_group](https://cmake.org/cmake/help/v3.0/command/source_group.html).
