### ISSUE TITLE
Build Linux platform executables on CI

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-gl-native#967]
Editing `platform/linux/linux.cmake` does not run CI right now (see #936).

We need to build these executables on CI.

**Comment by acalcutt** [comment]
This runs as part of the node ci already. It is running under ubuntu there though. Debian is not available in the github ci.

I've been meaning to test the build locally under debian 11, but i've had a busy week.

**Comment by acalcutt** [comment]
wait, i though we changed the node-ci to run on changed to windows/macos/linux last week

**Comment by acalcutt** [comment]
It looks like maybe we meant to add it, but didn't in https://github.com/maplibre/maplibre-gl-native/commit/343bfe443f4f389d791095329dc32c4f0bdd545e
