### ISSUE TITLE
Drawable Implementation: First Pass at Design

### ISSUE THREAD

**Issue by sjg-wdw** [maplibre/maplibre-gl-native#974]
Build enough of a drawable to support the simplest layer we can find.  Or the most basic, like Fill.

**Comment by ovivoda** [comment]
@TimSylvester please update the issue description once you decide how to proceed. 
Eg. What will you build in the drawable and which layer will you support first.

**Comment by TimSylvester** [comment]
Still in the very early stages, trying to establish where things are defined and used.  I will shortly create a draft PR for feedback on an initial stab at it, along with some discussion points.

**Comment by sjg-wdw** [comment]
I'm turning the architectural decisions into Issues, so you can close this Issue out.
