### ISSUE TITLE
Building in Xcode 12.4 getting -lmbgl-core library not found

### ISSUE THREAD

**Issue by nnhubbard** [maplibre/maplibre-gl-native#99]
I followed the install instructions and then used `make iproj` and tried to build the iosapp scheme, but I keep getting the error: 

```
ld: library not found for -lmbgl-core
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Is there any way to solve this?

Xcode 12.4
macOS 11.4

**Comment by roblabs** [comment]
I checked to see if the main or the metal branches were having this issue, but I was not able to replicate the issue (steps were `make iproj`, then use Xcode UI to build the `iosapp` scheme).  The scheme built fine for me.

Ideas to try:
* Review the steps for testing from the command line, see the [iOS build section](https://github.com/maplibre/maplibre-gl-native#ios-1).  The Makefile for tests points to other schemes, which have passed Continuous Integration tests done before release.
* The `make iproj` step sets dependencies and paths, then opens the Xcode version based on: `xcode-select -print-path`
* Be sure to checkout out a release by its tag and ensure that builds
* `make clean` as a last resort

I added the commit https://github.com/maplibre/maplibre-gl-native/commit/9a49fa16c9586916f8920e60170878893b67b8fc as some basic notes on how to checkout a particular release based on its tag.  Those notes will work for Android or iOS.

**Comment by nnhubbard** [comment]
The issue seemed to be due to a configuration conflict. I got a new computer and the build is successful.

**Comment by ankb9x** [comment]
1. In maplibre-gl-native/platform/ios/platform/ios, open project iOS Example (Open ios.xcworkspace)
2. Selected "dynamic" target, go to Build Settings / Search Paths / Librarys Search Paths
3. Change library search paths to static libmbgl-core.a, libmblg-vender-csscolorparser.a .... by add paths
"$(PROJECT_DIR)/../../build/ios/ArchiveIntermediates/dynamic/IntermediateBuildFilesPath/UninstalledProducts/iphonesimulator",
"$(PROJECT_DIR)/../../build/ios/ArchiveIntermediates/dynamic/IntermediateBuildFilesPath/UninstalledProducts/iphoneos",

It worked for me

**Comment by wipfli** [comment]
Ah nice, could this be change in a config file @ankb9x? If yes, would you be interested to file a pull request?

**Comment by ntadej** [comment]
Note this is a 2 year old version of Xcode. Is it even still supported by Apple?

**Comment by ankb9x** [comment]
> Note this is a 2 year old version of Xcode. Is it even still supported by Apple?
I use Xcode14
- If I open Xcode and building `dynamic` target, It's OK
- But If I using xcodebuild to build xcframework by
`make xcframework BUILDTYPE=Release`
-> It gives error
`ld: library not found for -lmbgl-core`
So, I fixed by change  library search paths of static -> It run
